#!/usr/bin/env bash

__rvm_notes_warning_var()
{
  for __var in RUBYOPT RUBYLIB
  do
    if eval "[[ -n \"\${${__var}:-}\" ]]"
    then
      rvm_warn "
  * WARNING: You have <code>${__var}</code> <warn>set in your current environment.
    This may cause rubies to not work as you expect them to as it is not supported
    by all of them If errors show up, please try unsetting <code>${__var}</code> <warn>first.
"
    fi
  done
}

__rvm_notes_warning_var
