#!/usr/bin/env bash

__rvm_notes_warning_rvm_in_usr()
{
  if
    [[ -x /usr/local/bin/rvm ]]
  then
    rvm_warn "
  * WARNING: you have <code>/usr/local/bin/rvm</code><warn>, it's most likely a bug of old installation, in most cases it's safe to remove it:

    <code>rm /usr/local/bin/rvm</code>
"
  fi
}

__rvm_notes_warning_rvm_in_usr
