#!/usr/bin/env bash

__rvm_notes_warning_apt_get_rvm()
{
  if [[ "$rvm_path" == "/usr/share/ruby-rvm" ]]
  then
    rvm_warn "
  * WARNING: You are using apt-get broken RVM, you should now:
    <code>
      sudo apt-get --purge remove ruby-rvm
      sudo \command \rm -rf /usr/share/ruby-rvm /etc/rvmrc /etc/profile.d/rvm.sh
    </code>
    <warn>open new terminal and validate environment is clean from old rvm settings:

      <code>env | __rvm_grep rvm</code>

    <warn>install RVM:

      <code>curl -L https://get.rvm.io | bash -s stable --autolibs=enable</code>

    <warn>for details check:

      https://stackoverflow.com/a/9056395/497756
"
  fi
}

__rvm_notes_warning_apt_get_rvm
