#!/usr/bin/env bash

__rvm_notes_warning_rvm_group()
{
  if
    [[ "$rvm_path" == "/usr/local/rvm" ]] || (( UID == 0 ))
  then
    rvm_warn "  * Please do NOT forget to add your users to the <code>rvm</code> group.\n" \
             "    The installer no longer auto-adds root or users to the rvm group. Admins must do this.\n" \
             "    Also, please note that group memberships are ONLY evaluated at login time.\n" \
             "    This means that users must log out then back in before group membership takes effect!"
  fi
}

__rvm_notes_warning_rvm_group
