#!/usr/bin/env bash

__rvm_notes_warning_gem_home()
{
  if
    [[ -n "${GEM_HOME:-}" ]] && ! [[ "${GEM_HOME}" == "$rvm_path/"* ]]
  then
    rvm_warn "  * WARNING: you have set <code>GEM_HOME=\"${GEM_HOME}\"</code>\n" \
             "    <warn>This is conflicting with RVM. Make sure to call:\n\n" \
             "          <code>unset GEM_HOME</code>\n"
  fi
}

__rvm_notes_warning_gem_home
