#!/usr/bin/env bash

__rvm_notes_warning_profile()
{
  if
    [[ ${rvm_ignore_dotfiles_flag:-0} == 0 ]] &&
    [[ -f "$HOME/.profile" ]] && ! [[ "$rvm_path" == "/usr/local/rvm" || $UID == 0 ]]
  then
    for __var in "$HOME/.bash_profile" "$HOME/.bash_login"
    do
      if
        [[ -f "${__var}" ]]
      then
        __rvm_grep -E '(source|\.).+profile' "${__var}" >/dev/null 2>&1 ||
        {
          rvm_warn "
  * WARNING: <code>~/.profile</code> <warn>file found. To load it into your shell, add the following line to <code>${__var}</code><warn>:

      <code>source ~/.profile</code>
"
        }
        break
      fi
    done
  fi
}

__rvm_notes_warning_profile
