#!/usr/bin/env bash

__rvm_notes_warning_loading_script()
{
  if
    [[ ${rvm_ignore_dotfiles_flag:-0} == 0 ]] &&
    [[ -f /etc/profile.d/rvm.sh ]] &&
    ! __rvm_grep rvm_stored_umask /etc/profile.d/rvm.sh >/dev/null
  then
    rvm_warn "  * WARNING: your RVM loading script <code>/etc/profile.d/rvm.sh</code> <warn>is deprecated\n" \
             "    and causes you to have <code>umask g+w</code> <warn>set in your shell.\n" \
             "    Run <code>rvm get master --auto-dotfiles</code> <warn>again to fix your scripts."
  fi
}

__rvm_notes_warning_loading_script
