#!/usr/bin/env bash

__rvm_notes_warning_rvm_configure_env()
{
  if
    [[ -f /etc/rvmrc && -s /etc/rvmrc ]] &&
    __rvm_grep 'rvm_configure_env=.*/opt/sm' /etc/rvmrc >/dev/null 2>&1
  then
    rvm_warn "  * WARNING: you have <code>rvm_configure_env</code> <warn>in <code>/etc/rvmrc</code><warn>, run the following to fix:<code>\n\n" \
             "      sudo sed -i'' -e \"/rvm_configure_env=.*\/opt\/sm/d\" /etc/rvmrc\n" \
             "      rvm autolibs smf"
  fi
}

__rvm_notes_warning_rvm_configure_env
