#!/usr/bin/env bash

if [[ -z "$test_setup_flag" ]] ; then
  rvm_path=~/.rvm-test ; export rvm_path
  ./install >/dev/null
  source scripts/rvm
  rubies=$(\ls test/rubies/)

  initialize_rvm() {
    __rvm_cleanup_variables
    __rvm_load_rvmrc
    __rvm_initialize
  }

  # Load the Bash Test::Unit Framework
  source test/btu
  btu_init

  test_setup_flag=1
fi

