#!/bin/bash

if [ -z "$test_setup_flag" ] ; then
  rvm_dir=~/.rvm-test ; export rvm_dir
  ./install
  source scripts/rvm
  rubies=$(\ls test/rubies/)

  initialize_rvm() {
    __rvm_cleanup_variables
    __rvm_load-rvmrc
    __rvm_initialize
    __rvm_load_defaults
  }

  # Load the Bash Test::Unit Framework
  source test/btu
  btu_init

  test_setup_flag=1
fi

