#!/usr/bin/env bash

echo "Snapshotting the current environment gem list into snapshot.gems"
file_name="snapshot.gems"
echo '# system snapshot gemset file' > snapshot.gems
for gem in $(gem list | sed 's#[\(|\)]##g' | sed 's#, #,#g' | \tr ' ' ';') ; do
  name="$(echo $gem | awk -F';' '{print $1}')"
  versions="$(echo $gem | awk -F';' '{print $2}' | sed 's#,# #g')"
  for version in $versions ; do
    echo "$name -v$version" >> $file_name
  done ; unset version versions
done ; unset file_name

exit $?
