version: 2
mergeable:
  - when: pull_request.*
    validate:
    - do: description
      no_empty:
        enabled: true
        message: Description should not be empty. Provide details with **what** was changed, **why** it was changed, and **how** it was changed.
    - do: label
      and:
      - no_empty:
          enabled: true
      - must_exclude:
          regex: duplicate|feedback|invalid|wont|progress
    - do: milestone
      no_empty:
        enabled: true
    - do: dependent
      changed:
        file: '*'
        files: ['CHANGELOG.md']
        message: Missing CHANGELOG entry
    - do: dependent
      changed:
        file: 'binscripts/rvm-installer'
        files: ['binscripts/rvm-installer.asc']
        message: Installer is missing updated signature.
    - do: dependent
      changed:
        files: ['config/known', 'config/known_strings', 'config/md5', 'config/sha512']
        message: New ruby version needs to be listed as known and with signatures.
