#!/usr/bin/env bash

function bundle_not_found()
{
  printf "%b" "$(tput setaf 1)ERRRO: Gem bundler is not installed, run \`gem install bundler\` first.$(tput sgr0)\n"
  exit 127
}

# in rvm warn about missing gem
if [[ -n "${GEM_HOME:-}" ]]
then
  bundle_not_found
else
  current_bundle="$(which $0)"
  PATH=":${PATH}:"
  PATH="${PATH//:${current_bundle}:/:}"
  PATH="${PATH#:}"
  PATH="${PATH%:}"
  if which bundle >/dev/null 2>&1
  then
    bundle "$@"
  else
    bundle_not_found
  fi
fi
