#!/usr/bin/env bash

if [[ -f /etc/rvmrc ]] ; then source /etc/rvmrc ; fi
if [[ -f "$HOME/.rvmrc" ]] ; then source "$HOME/.rvmrc" ; fi
if [[ -z "$rvm_path" ]] ; then unset rvm_path ; fi

if [[ -z "$rvm_path" ]] ; then
  unset rvm_path
  if [[ "root" = "$(whoami)" ]] ; then
    rvm_path="/usr/local/rvm"
  else
    if [[ -d "$HOME/.rvm" ]] && [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
      rvm_path="$HOME/.rvm"
    elif [[ -d "/usr/local/rvm" ]] && [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
      rvm_path="${rvm_path:-"/usr/local/rvm"}"
    fi
  fi
fi

rvm_scripts_path="${rvm_scripts_path:-"$rvm_path/scripts"}"
source $rvm_scripts_path/rvm

unset rvm_interactive

rvm "$*"
