#!/usr/bin/env bash

if [[ -z "$rvm_ignore_rvmrc" ]]; then
  [[ -s /etc/rvmrc ]] && source /etc/rvmrc
  [[ -s "$HOME/.rvmrc" ]] && source "$HOME/.rvmrc"
fi

rvm_path="${rvm_path:-$HOME/.rvm}"
mkdir -p $rvm_path/src/
cd $rvm_path/src

rm -rf ./rvm/ && git clone --depth 1 git://github.com/wayneeseguin/rvm.git
cd rvm
# v v v This is a godo idea however it does not preserve the executible bit.
# Needs more thought, perhaps a simple sed instead.
# dos2unix scripts/* >/dev/null 2>&1
bash scripts/install
