#!/usr/bin/env ruby

Dir.chpwd( File.join( ENV["GEM_HOME"], "gems", "rvm-#{RVM::Version::STRING}", "releases" ) ) do

  printf "Extracting rvm-#{RVM::Version::STRING}.tar.gz"

  %x{tar zxf rvm-#{RVM::Version::STRING}.tar.gz}

  Dir.chpwd( "rvm-#{RVM::Version::STRING}" ) do

  printf "Running RVM install script"

    puts %x{bash ./scripts/install}

  end

end

