#!/usr/bin/env bash

if [[ -n "$rvm_path" && -s "$rvm_path/scripts/rvm" ]]; then
  source "$rvm_path/scripts/rvm" > /dev/null 2>&1

elif [[ -s "/usr/local/lib/rvm" ]]; then
  source "/usr/local/lib/rvm" > /dev/null 2>&1

elif [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm" > /dev/null 2>&1

elif [[ -s "/usr/local/rvm/scripts/rvm" ]]; then
  source "/usr/local/rvm/scripts/rvm" > /dev/null 2>&1
else
  echo "Unable to detect rvm, please manually set the rvm_path env variable." >&2
  exit 1
fi

[[ -s "$rvm_path/environments/default" ]] && source "$rvm_path/environments/default"

rvm_promptless=1 rvm rvmrc load > /dev/null 2>&1

exec ruby "$@"
