#!/usr/bin/env bash

prefix="PATH='$PATH'"
if [[ -n "${BUNDLE_PATH:-""}" ]] ; then prefix="BUNDLE_PATH='$BUNDLE_PATH' $prefix" ; fi
if [[ -n "${GEM_HOME:-""}" ]]    ; then prefix="GEM_HOME='$GEM_HOME' $prefix" ; fi
if [[ -n "${GEM_PATH:-""}" ]]    ; then prefix="GEM_PATH='$GEM_PATH' $prefix" ; fi

eval "sudo" "/usr/bin/env $prefix $@"
# rvm_env_prefix="PATH='$PATH'"
# exec sudo -E /usr/bin/env "$rvm_env_prefix" "$@"
