#!/usr/bin/env bash

__rvm_make_failed_osx()
{
  __rvm_make_failed_osx_avira
}

__rvm_make_failed_osx_avira()
{
  if ps ax | __rvm_grep -v grep | __rvm_grep Avira.app &> /dev/null
  then
    rvm_error "\nIt seems that Avira antivirus is running. It has been reported to cause failures on ruby compilation.
Disable it for the time of the installation and try again."
  fi
}
