#!/usr/bin/env bash

__rvm_detect_xcode_version()
{
  \typeset version_file

  for version_file in \
    /Applications/Xcode.app/Contents/version.plist \
    /Developer/Applications/Xcode.app/Contents/version.plist
  do
    if
      [[ -f $version_file ]]
    then
      if
        [[ -x /usr/libexec/PlistBuddy ]]
      then
        /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" $version_file
      else
        __rvm_sed -n '/<key>CFBundleShortVersionString<\/key>/{n; s/^.*>\(.*\)<.*$/\1/; p;}' < $version_file
      fi

      return 0
    fi
  done

  if
    builtin command -v xcodebuild >/dev/null
  then
    xcodebuild -version | __rvm_sed -n '/Xcode/ {s/Xcode //; p;}'
    return 0
  fi

  return 1
}

__rvm_detect_xcode_clt_version()
{
  \typeset package version

  for package in \
    com.apple.pkg.DeveloperToolsCLI \
    com.apple.pkg.CLTools_Executables
  do
    if [[ -z "${version}" ]]
    then
      version="$(pkgutil --pkg-info $package 2>/dev/null | __rvm_awk '$1~/version:/{print $2}')"
    fi
  done

  echo "${version}"
}
