#!/usr/bin/env bash

__rvm_notes_opencollective()
{
  __rvm_warn "
<warning>Thanks for installing RVM 🙏</warning>
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: <code>https://opencollective.com/rvm/donate</code>
"
}

__rvm_notes_opencollective
