#!/usr/bin/env bash

__rvm_notes_opencollective()
{
  rvm_notify "<warn>Thanks for installing RVM 🙏</warn>
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: <code>https://opencollective.com/rvm/donate</code>

"
}

__rvm_notes_opencollective
