#!/usr/bin/env bash

requirements_osx_update_openssl_cert_run()
{
  if # older or missing
    [[ "$cert_file" -ot /Library/Keychains/System.keychain ]] ||
    [[ "$cert_file" -ot /System/Library/Keychains/SystemRootCertificates.keychain ]]
  then
    rvm_log "Updating certificates in '$cert_file'."
    security find-certificate -a -p /Library/Keychains/System.keychain > "$cert_file"
    security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain >> "$cert_file"
    "${ssl_binary%/openssl}/c_rehash" "$ssl_dir"
  else
    rvm_log "Certificates in '$cert_file' already are up to date."
  fi
}

requirements_osx_update_openssl_cert()
{
  [[ "Darwin" == "$(uname)" ]] || return 0

  typeset ssl_binary ssl_dir cert_file
  ssl_binary="${1:-$(which openssl)}"
  ssl_dir="$( "${ssl_binary}" version -d | awk -F'"' '{print $2}' )" #' fix formating
  cert_file="${ssl_dir}/cert.pem"
  case "${rvm_autolibs_flag}" in
    (0)
      rvm_debug "Skipping update of certificates in '$cert_file'."
      ;;
    (1)
      rvm_warn  "Skipping update of certificates in '$cert_file'."
      ;;
    (2)
      rvm_error  "Cowardly refusing update certificates in '$cert_file'."
      # FIXME https://github.com/wayneeseguin/rvm/issues/1655
      return 1
      ;;
    (*)
      requirements_osx_update_openssl_cert_run
      ;;
  esac
}

requirements_load()
{
  if
    is_a_function requirements_${1} ||
    is_a_function requirements_${1}_run
  then
    rvm_debug "requirements code for $1 already loaded"
  else
    [[ -s "$rvm_scripts_path/functions/requirements/$1" ]] ||
    {
      rvm_error "Requirements support for $1 is not implemented yet,
  report a bug here => https://github.com/wayneeseguin/rvm/issues"
      return 1
    }
    source "$rvm_scripts_path/functions/requirements/$1"
    if
      is_a_function requirements_${1} ||
      is_a_function requirements_${1}_run
    then
      rvm_debug "requirements code for $1 loaded"
    else
      rvm_error "Failed loading requirements for $1!"
      return 1
    fi
  fi
}

requirements_iterate()
{
  typeset -a list
  typeset element __handler
  __handler=$1
  shift

  list=( update-system rvm )
  while (( $# )) && [[ -z "$1" ]]
  do shift
  done
  if (( $# ))
  then list+=( "$@" )
  else list+=( ruby )
  fi

  for element in "${list[@]}"
  do ${__handler} "${element}" || return $?
  done
  true
}

requirements_run()
{
  typeset __type
  __type=$1
  shift
  requirements_load ${__type} || return $?
  if
    is_a_function requirements_${__type}
  then
    requirements_${__type} "$@" || return $?
  elif
    is_a_function requirements_${__type}_run
  then
    requirements_iterate requirements_${__type}_run "$@" || return $?
  fi
}

__rvm_filter_installed_packages_reset()
{
  packages_installed=()
  packages_missing=()
  packages_to_install=()
}

__rvm_filter_installed_package_check()
{
  if
    "$1" "$2"
  then
    packages_installed+=( "$2" )
  else
    case "$rvm_autolibs_flag" in
      (0|1)  packages_missing+=( "$2" ) ;; # just ignore
      (*) packages_to_install+=( "$2" ) ;; # 2+
    esac
  fi
}

__rvm_filter_installed_packages_summary()
{
  (( ${#packages_installed[@]} == 0 )) ||
  {
    _list="${packages_installed[*]}"
    rvm_debug "Found required packages: ${_list// /, }."
  }
  (( ${#packages_missing[@]} == 0 )) ||
  {
    _list="${packages_missing[*]}"
    if (( rvm_autolibs_flag == 0 ))
    then rvm_debug "Missing required packages: ${_list// /, }."
    else rvm_warn "Missing required packages: ${_list// /, }."
    fi
  }
}

__rvm_filter_installed_packages_install()
{
  (( ${#packages_to_install[@]} == 0 )) ||
  {
    _list="${packages_to_install[*]}"
    __rvm_log_command package_install_${_list// /_} "Installing required packages: ${_list// /, }." \
      "$1" "${packages_to_install[@]}" ||
      return $?
  }
}

__rvm_filter_installed_packages()
{
  typeset _package_installed_cmd _packages_install_cmd _package_name _list

  _package_installed_cmd="requirements_$1_lib_installed"
  _package_install_cmd="requirements_$1_libs_install"
  shift

  __rvm_filter_installed_packages_reset
  for _package_name
  do __rvm_filter_installed_package_check "${_package_installed_cmd}" "${_package_name}"
  done
  __rvm_filter_installed_packages_summary
  __rvm_filter_installed_packages_install "${_package_install_cmd}"
}

__rvm_try_sudo()
{
  typeset -a command_to_run
  command_to_run=()
  case "$rvm_autolibs_flag" in
    (0|1)
      (( UID == 0 )) || return 0 # do not run nothing if it would require sudo
      ;;
    (*)
      (( UID == 0 )) || command_to_run+=( sudo )
      ;;
  esac
  "${command_to_run[@]}" "$@"
}
