#!/usr/bin/env bash

function bundle()
{
  if (unset bundle ; command -v bundle) >/dev/null 2>&1
  then
    true
  else
    if command -v gem >/dev/null 2>&1
    then
      # Ensure that Bundler is installed. Install it if it is not.
      printf "The rubygem 'bundler' is not installed. Installing it now.\n"
      gem install bundler
    else
      printf "Cannot use 'bundler' as 'gem' was not found in the path!.\n"
    fi
  fi

  if (unset bundle ; command -v bundle) >/dev/null 2>&1
  then
    if [[ "$*" =~ 'install' ]]
    then
      printf "Bundling your gems. This may take a few minutes on first run.\n"
      command bundle "$@" --binstubs=$GEM_HOME/bin
    else
      command bundle "$@"
    fi
  fi
}
