#!/usr/bin/env bash

#
# rm -rf with *some* safeguards in place.
#
__rvm_rm_rf()
{
  local result target="${1%%+(/|.)}"

  case "${target}" in

    (*(/|.)@(|/Applications|/Developer|/Guides|/Information|/Library|/Network|/System|/User|/Users|/Volumes|/backups|/bdsm|/bin|/boot|/cores|/data|/dev|/etc|/home|/lib|/lib64|/mach_kernel|/media|/misc|/mnt|/net|/opt|/private|/proc|/root|/sbin|/selinux|/srv|/sys|/tmp|/usr|/var))
        result=1
      ;;

    *)
      if [[ -n "${target}" && -d "${target}" ]] ; then
        \rm -rf "${target}"
        result=0
      else
        result=1
      fi
      ;;
  esac

  return $result
}

