#!/usr/bin/env bash

#
# rm -rf with *some* safeguards in place.
#
__rvm_rm_rf()
{
  local result=1 target="${1%%+(/|.)}"

  #NOTE: RVM Requires extended globbing shell feature turned on.
  case "${target}" in

    (*(/|.)@(|/Applications|/Developer|/Guides|/Information|/Library|/Network|/System|/User|/Users|/Volumes|/backups|/bdsm|/bin|/boot|/cores|/data|/dev|/etc|/home|/lib|/lib64|/mach_kernel|/media|/misc|/mnt|/net|/opt|/private|/proc|/root|/sbin|/selinux|/srv|/sys|/tmp|/usr|/var))
        false
      ;;

    *)
      if [[ -n "${target}"  ]] ; then

        if [[ -d "${target}" ]] ; then # Directory
          \rm -rf "${target}"
          result=0
        elif [[ -f "${target}" || -L "${target}" ]]; then # File / Symbolic Link
          \rm -f "${target}"
          result=0
        fi

      fi
      ;;
  esac

  return $result
}

