#!/usr/bin/env bash

source "$rvm_scripts_path/functions/osx-ssl-certs"

\typeset osx_ssl_certs_curl_ca_bundle

__rvm_osx_ssl_certs_curl_cert_find_path()
{
  # Find correct curl CA Bundle path
  # See: https://curl.haxx.se/docs/sslcerts.html

  osx_ssl_certs_curl_ca_bundle="$CURL_CA_BUNDLE"

  if [[ ! -f "$osx_ssl_certs_curl_ca_bundle" ]]
  then
    \typeset curl_bin
    curl_bin="$(type -p curl)"

    osx_ssl_certs_curl_ca_bundle="${curl_bin%/bin/curl}/share/curl/curl-ca-bundle.crt"
  fi

  rvm_debug "Expected cURL certificate bundle location: ${osx_ssl_certs_curl_ca_bundle}"
}

__rvm_osx_ssl_certs_curl_status()
{
  if [[ -f "$osx_ssl_certs_curl_ca_bundle" ]]
  then
    rvm_debug "Reading cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle}"

    __rvm_osx_ssl_certs_status_for_path "$osx_ssl_certs_curl_ca_bundle"
  else
    rvm_debug "cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle} not found."
  fi
}
__rvm_osx_ssl_certs_curl_update()
{
  if [[ -f "$osx_ssl_certs_curl_ca_bundle" ]]
  then
    rvm_debug "Updating cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle}"

    __rvm_osx_ssl_certs_update_for_path "$osx_ssl_certs_curl_ca_bundle"
  else
    rvm_debug "cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle} not found. Skipping cURL update."
  fi
}

__rvm_osx_ssl_certs_curl_cert_find_path
