#!/usr/bin/env bash

source "$rvm_scripts_path/functions/osx-ssl-certs"

\typeset osx_ssl_certs_curl_ca_bundle

__rvm_osx_ssl_certs_curl_cert_find_path()
{
  # Find correct curl CA Bundle path
  # See: https://curl.haxx.se/docs/sslcerts.html

  osx_ssl_certs_curl_ca_bundle="$CURL_CA_BUNDLE"

  if [ ! -f "$osx_ssl_certs_curl_ca_bundle" ]
  then
    \typeset curl_bin
    curl_bin="$(type -p curl)"

    osx_ssl_certs_curl_ca_bundle="${curl_bin%/bin/curl}/share/curl/curl-ca-bundle.crt"
  fi
}

__rvm_osx_ssl_certs_curl_status()
{
  if [ -f "$osx_ssl_certs_curl_ca_bundle" ];  then
    __rvm_osx_ssl_certs_status_for_path "$osx_ssl_certs_curl_ca_bundle"
  fi
}
__rvm_osx_ssl_certs_curl_update()
{
  if [ -f "$osx_ssl_certs_curl_ca_bundle" ];  then
    __rvm_osx_ssl_certs_update_for_path "$osx_ssl_certs_curl_ca_bundle"
  fi
}

__rvm_osx_ssl_certs_curl_cert_find_path
