#!/usr/bin/env bash

__rvm_osx_ssl_certs_curl_cert_find_path()
{
  # Find correct curl CA Bundle path
  # See: https://curl.haxx.se/docs/sslcerts.html

  \typeset osx_ssl_certs_curl_ca_bundle

  osx_ssl_certs_curl_ca_bundle="$CURL_CA_BUNDLE"

  if [[ ! -f "$osx_ssl_certs_curl_ca_bundle" ]]
  then
    \typeset curl_bin
    curl_bin="$(type -p curl)"

    osx_ssl_certs_curl_ca_bundle="${curl_bin%/bin/curl}/share/curl/curl-ca-bundle.crt"
  fi

  rvm_debug "Expected cURL certificate bundle location: ${osx_ssl_certs_curl_ca_bundle}"

  if [[ -f "$osx_ssl_certs_curl_ca_bundle" ]]
  then
    rvm_debug "Found cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle}"
    echo $osx_ssl_certs_curl_ca_bundle
  else
    rvm_warn "cURL certificate bundle ${osx_ssl_certs_curl_ca_bundle} not found"
    echo ""
  fi
}
