#!/usr/bin/env bash

export escape_flag _first _second
escape_flag=1
_first=${__array_start}
_second=$[__array_start + 1]

__rvm_md5_for()
{
  if builtin command -v md5 > /dev/null; then
    echo "$1" | md5
  elif builtin command -v md5sum > /dev/null ; then
    echo "$1" | md5sum | awk '{print $1}'
  else
    rvm_error "Neither md5 nor md5sum were found in the PATH"
    return 1
  fi

  return 0
}

__rvm_sha256_for()
{
  if builtin command -v sha256sum > /dev/null ; then
    echo "$1" | sha256sum | awk '{print $1}'
  elif builtin command -v sha256 > /dev/null ; then
    echo "$1" | sha256 | awk '{print $1}'
  elif builtin command -v shasum > /dev/null ; then
    echo "$1" | shasum -a256 | awk '{print $1}'
  else
    rvm_error "Neither sha256sum nor shasum found in the PATH"
    return 1
  fi

  return 0
}

__rvm_md5_for_contents()
{
  if builtin command -v md5 > /dev/null
  then
    echo "$1" | cat - "$1" | md5
  elif builtin command -v md5sum > /dev/null
  then
    echo "$1" | cat - "$1" | md5sum | awk '{print $1}'
  else
    rvm_error "Neither md5 nor md5sum were found in the PATH"
    return 1
  fi

  return 0
}

__rvm_sha256_for_contents()
{
  if builtin command -v sha256sum > /dev/null ; then
    echo "$1" | cat - "$1" | sha256sum | awk '{print $1}'
  elif builtin command -v sha256 > /dev/null ; then
    echo "$1" | cat - "$1" | sha256 | awk '{print $1}'
  elif builtin command -v shasum > /dev/null ; then
    echo "$1" | cat - "$1" | shasum -a256 | awk '{print $1}'
  else
    rvm_error "Neither sha256sum nor shasum found in the PATH"
    return 1
  fi

  return 0
}

__rvm_rvmrc_key()
{
  printf "%b" "$1" | tr '[#/.=]' _
  return $?
}

__rvm_reset_rvmrc_trust()
{
  if [[ "$1" == all ]]
  then
    echo "" > "$rvm_user_path/rvmrcs"
  else
    "$rvm_scripts_path/db" "$rvm_user_path/rvmrcs" \
      "$(__rvm_rvmrc_key "$1")" "delete" >/dev/null 2>&1
  fi
}

__rvm_trust_rvmrc()
{
  __rvm_reset_rvmrc_trust "$1"
  "$rvm_scripts_path/db" "$rvm_user_path/rvmrcs" \
    "$(__rvm_rvmrc_key "$1")" "1;$(__rvm_md5_for_contents "$1")$(__rvm_sha256_for_contents "$1")" >/dev/null 2>&1
  return $?
}

__rvm_untrust_rvmrc()
{
  __rvm_reset_rvmrc_trust "$1"
  "${rvm_scripts_path:-"$rvm_path/scripts"}/db" "$rvm_user_path/rvmrcs" \
    "$(__rvm_rvmrc_key "$1")" "0;$(__rvm_md5_for_contents "$1")$(__rvm_sha256_for_contents "$1")" >/dev/null 2>&1
}

__rvm_rvmrc_stored_trust()
{
  "${rvm_scripts_path:-"$rvm_path/scripts"}/db" "$rvm_user_path/rvmrcs" \
    "$(__rvm_rvmrc_key "$1")"
  return $?
}

__rvm_rvmrc_tools()
{
  export escape_flag
  typeset rvmrc_action rvmrc_path saveIFS trust rvmrc_ruby

  escape_flag=1

  rvmrc_action="$1"
  (( $# )) && shift || true

  if [[ "${rvmrc_action}" == "create" ]]
  then
    rvmrc_ruby="${1:-${MY_RUBY_HOME##*/}}"
    rvmrc_path="$(builtin cd "$PWD" >/dev/null 2>&1; pwd)"
  elif [[ "${1:-}" == "all" ]]
  then
    rvmrc_path="all"
  else
    rvmrc_path="$(builtin cd "${1:-$PWD}" >/dev/null 2>&1; pwd)"
  fi
  (( $# )) && shift || true

  if (( $# ))
  then rvmrc_path="${rvmrc_path}/$1"

  elif [[ -s "${rvmrc_path}/.rvmrc" ]]
  then rvmrc_path="${rvmrc_path}/.rvmrc"

  elif [[ -s "${rvmrc_path}/.versions.conf" ]]
  then rvmrc_path="${rvmrc_path}/.versions.conf"

  elif [[ -f "${rvmrc_path}/.ruby-version" ]]
  then rvmrc_path="${rvmrc_path}/.ruby-version"

  elif [[ -f "${rvmrc_path}/.rbfu-version" ]]
  then rvmrc_path="${rvmrc_path}/.rbfu-version"

  elif [[ -f "${rvmrc_path}/.rbenv-version" ]]
  then rvmrc_path="${rvmrc_path}/.rbenv-version"

  elif [[ -f "${rvmrc_path}/Gemfile" ]]
  then rvmrc_path="${rvmrc_path}/Gemfile"

  elif [[ "${rvmrc_path}" == "all" ]]
  then rvmrc_path="all"

  else rvmrc_path="${rvmrc_path}/.rvmrc"
  fi

  case "$rvmrc_action" in
    create)
      (
        rvm_ruby_string="${rvmrc_ruby}"
        rvm_create_flag=1 __rvm_use
        case "${rvmrc_path}" in
          (*/.rvmrc|*/--rvmrc)
            __rvm_set_rvmrc
            ;;
          (*/.ruby-version|*/--ruby-version)
            __rvm_set_ruby_version
            ;;
          (*/.versions.conf|*/--versions-conf)
            __rvm_set_versions_conf
            ;;
          (*)
            rvm_error "Unrecognized project file format"
            return 1
            ;;
        esac
      )
      ;;
    reset)
      __rvm_reset_rvmrc_trust "$rvmrc_path"
      echo "Reset trust for $rvmrc_path"
      ;;
    trust)
      __rvm_trust_rvmrc "$rvmrc_path"
      echo "Marked $rvmrc_path as trusted"
      ;;

    untrust)
      __rvm_untrust_rvmrc "$rvmrc_path"
      echo "Marked $rvmrc_path as untrusted"
      ;;

    trusted)
      if [[ -f "$rvmrc_path" ]]
      then
        saveIFS=$IFS
        IFS=$';'
        trust=($(__rvm_rvmrc_stored_trust "$rvmrc_path"))
        IFS=$saveIFS

        if [[ "${trust[${_second}]:-'#'}" != "$(__rvm_md5_for_contents "$rvmrc_path")$(__rvm_sha256_for_contents "$rvmrc_path")" ]]
        then
          echo "The rvmrc at '$rvmrc_path' contains unreviewed changes."
        elif [[ "${trust[${_first}]}" == '1' ]]
        then
          echo "The rvmrc at '$rvmrc_path' is currently trusted."
        elif [[ "${trust[${_first}]}" == '0' ]]
        then
          echo "The rvmrc at '$rvmrc_path' is currently untrusted."
        else
          echo "The trustiworthiness of '$rvmrc_path' is currently unknown."
        fi
      else
        echo "There is no $rvmrc_path"
      fi
      ;;

    is_trusted)
      if [[ -f "$rvmrc_path" ]]
      then
        saveIFS=$IFS
        IFS=$';'
        trust=($(__rvm_rvmrc_stored_trust "$rvmrc_path"))
        IFS=$saveIFS

        if [[ "${trust[${_second}]:-'#'}" != "$(__rvm_md5_for_contents "$rvmrc_path")$(__rvm_sha256_for_contents "$rvmrc_path")" ]]
        then
          return 1
        elif [[ "${trust[${_first}]}" == '1' ]]
        then
          return 0
        else
          return 1
        fi
      else
        return 1
      fi
      ;;

    load)
      rvm_rvmrc_cwd="" rvm_trust_rvmrcs_flag=1  \
        __rvm_project_rvmrc "$(dirname "$rvmrc_path")" "$(basename "$rvmrc_path")"
      ;;

    try_to_read_ruby)
      case "$rvmrc_path" in
        (*/.rvmrc)
          if ! __rvm_rvmrc_tools is_trusted "$(dirname "$rvmrc_path")"  "$(basename "$rvmrc_path")"
          then
            # subprocess to not mess with current process variables
            ( __rvm_project_rvmrc "$(dirname "$rvmrc_path")"  "$(basename "$rvmrc_path")" >/dev/null 2>&1 )
          fi

          if __rvm_rvmrc_tools is_trusted "$(dirname "$rvmrc_path")" "$(basename "$rvmrc_path")"
          then
            rvm_action="${rvm_action:-use}"
            rvm_ruby_string="$(
              rvm_rvmrc_cwd=""
              rvm_trust_rvmrcs_flag=1
              __rvm_project_rvmrc "$(dirname "$rvmrc_path")" "$(basename "$rvmrc_path")" >/dev/null 2>&1
              __rvm_env_string
            )"
            rvm_ruby_strings="$rvm_ruby_string"
          else
            rvm_action="error"
            rvm_error_message="The give path does not contain '$(basename "$rvmrc_path")' (or it is not trusted): '$(dirname "$rvmrc_path")' rest of params: '$@'"
          fi
        ;;
        (*)
          rvm_action="${rvm_action:-use}"
          rvm_ruby_string="$(
            rvm_rvmrc_cwd=""
            rvm_trust_rvmrcs_flag=1
            __rvm_project_rvmrc "$(dirname "$rvmrc_path")" "$(basename "$rvmrc_path")" >/dev/null 2>&1
            __rvm_env_string
          )"
          rvm_ruby_strings="$rvm_ruby_string"
        ;;
      esac
      ;;

    *)
      echo "Usage: rvm rvmrc {trust,untrust,trusted,load,reset,is_trusted,try_to_read_ruby}"
      return 1
      ;;
  esac

  unset escape_flag
  return $?
}

__rvm_check_rvmrc_trustworthiness()
{
  typeset saveIFS trust result
  # Trust when they have the flag... of doom!
  if [[ -n "$1" && ${rvm_trust_rvmrcs_flag:-0} == 0 ]]
  then
    saveIFS="$IFS"
    IFS=$';'
    trust=( $( __rvm_rvmrc_stored_trust "$1" ) )
    IFS="$saveIFS"

    if [[ "${trust[${_second}]:-'#'}" != "$(__rvm_md5_for_contents "$1")$(__rvm_sha256_for_contents "$1")" ]]
    then
      __rvm_ask_to_trust "$1"
    else
      [[ "${trust[${_first}]}" == '1' ]]
    fi

  fi
  result=$?
  unset escape_flag
  return $result
}

__rvm_display_rvmrc()
{
  typeset _rvmrc_base
  _rvmrc_base="$(basename "${_rvmrc}")"
  printf "
====================================================================================
= %-80s =
= After reading the file, you will be prompted again for 'yes or no' to set        =
= the trust level for this particular version of the file.                         =
=                                                                                  =
= %-80s =
= changes, and may change the trust setting manually at any time.                  =
====================================================================================
(( press a key to review the ${_rvmrc_base} file ))
" \
"The contents of the ${_rvmrc_base} file will now be displayed." \
"Note: You will be re-prompted each time the ${_rvmrc_base} file's contents change"
builtin read -n 1 -s -r anykey

printf "%b" "${rvm_warn_clr}"
command cat -v "${_rvmrc}"
printf "%b" "${rvm_reset_clr}"

  printf "
====================================================================================
= %-80s =
====================================================================================
= %-80s =
= %-80s =
= Note that if the contents of the file change, you will be re-prompted to         =
= review the file and adjust its trust settings. You may also change the           =
= trust settings manually at any time with the 'rvm rvmrc' command.                =
====================================================================================

" \
"Viewing of ${_rvmrc} complete." \
"Trusting an ${_rvmrc_base} file means that whenever you cd into this directory," \
"RVM will run this ${_rvmrc_base} shell script."
}

__rvm_ask_to_trust()
{
  typeset trusted value anykey _rvmrc
  _rvmrc="${1}"

  if [[ ! -t 0 ]] || (( ${rvm_promptless:=0} == 1 )) || [[ -n "$MC_SID" ]]
  then
    return 2
  fi

  printf "====================================================================================
= NOTICE                                                                           =
====================================================================================
= %-80s =
= This is a shell script and therefore may contain any shell commands.             =
=                                                                                  =
= Examine the contents of this file carefully to be sure the contents are          =
= safe before trusting it! ( Choose v[iew] below to view the contents )            =
====================================================================================
" \
"RVM has encountered a new or modified $(basename "${_rvmrc}") file in the current directory"
  trusted=0
  while (( ! trusted ))
  do
    printf "Do you wish to trust this $(basename "${_rvmrc}") file? (%b)\n" "${_rvmrc}"
    printf "%b" 'y[es], n[o], v[iew], c[ancel]> '

    builtin read response
    value="$(echo -n "${response}" | tr '[[:upper:]]' '[[:lower:]]' | __rvm_strip)"

    case "${value:-n}" in
      v|view)
        __rvm_display_rvmrc
        ;;
      y|yes)
        trusted=1
        ;;
      n|no)
        break
        ;;
      c|cancel)
        return 1
        ;;
    esac
  done

  if (( trusted ))
  then
    __rvm_trust_rvmrc "$1"
    return 0
  else
    __rvm_untrust_rvmrc "$1"
    return 1
  fi
}

# Checks the rvmrc for the given directory. Note that if
# argument is passed, it will be used instead of pwd.
__rvm_project_rvmrc()
{
  export __rvm_project_rvmrc_lock
  : __rvm_project_rvmrc_lock:${__rvm_project_rvmrc_lock:=0}
  : __rvm_project_rvmrc_lock:$((__rvm_project_rvmrc_lock+=1))
  if (( __rvm_project_rvmrc_lock > 1 ))
  then return 0 # no nesting
  fi

  typeset working_dir requested_file found_file rvm_trustworthiness_result

  # Get the first argument or the pwd.
  working_dir="${1:-"$PWD"}"
  requested_file="${2:-}"

  while :
  do
    if [[ -z "$working_dir" || "$HOME" == "$working_dir" || "/" == "$working_dir" ]]
    then
      if [[ -n "${rvm_current_rvmrc:-""}" ]]
      then
        __rvm_remove_rvm_from_path ; __rvm_conditionally_add_bin_path
        if (( ${rvm_project_rvmrc_default:-0} == 1 ))
        then
          __rvm_load_environment "default"
        elif [[ -n "${rvm_previous_environment:-""}" ]]
        then
          __rvm_load_environment "$rvm_previous_environment"
        fi
        unset rvm_current_rvmrc rvm_previous_environment
      fi
      break
    else
      if [[ -n "${requested_file}" && -f "$working_dir/${requested_file}" ]]
      then found_file="$working_dir/${requested_file}"

      elif [[ -f "$working_dir/.rvmrc" ]]
      then found_file="$working_dir/.rvmrc"

      elif [[ -f "$working_dir/.versions.conf" ]]
      then found_file="$working_dir/.versions.conf"

      elif [[ -f "$working_dir/.ruby-version" ]]
      then found_file="$working_dir/.ruby-version"

      elif [[ -f "$working_dir/.rbfu-version" ]]
      then found_file="$working_dir/.rbfu-version"

      elif [[ -f "$working_dir/.rbenv-version" ]]
      then found_file="$working_dir/.rbenv-version"

      elif [[ -f "$working_dir/Gemfile" ]]
      then found_file="$working_dir/Gemfile"
      fi

      if [[ -n "${found_file}" ]]
      then
        if [[ "${rvm_current_rvmrc:-""}" != "${found_file}" ]]
        then
          if __rvm_conditionally_do_with_env __rvm_load_project_config "${found_file}"
          then true
          else
            rvm_trustworthiness_result=$?
            unset __rvm_project_rvmrc_lock
            return "$rvm_trustworthiness_result"
          fi
        fi
        break
      else
        working_dir="$(dirname "$working_dir")"
      fi
    fi
  done

  unset __rvm_project_rvmrc_lock
  return $?
}

__rvm_load_project_config()
{
  typeset __gemfile
  : rvm_autoinstall_bundler_flag:${rvm_autoinstall_bundler_flag:=0}
  case "$1" in
    (*/.rvmrc)
      if __rvm_check_rvmrc_trustworthiness "$1"
      then
        __rvm_remove_rvm_from_path ; __rvm_conditionally_add_bin_path
        rvm_previous_environment="$(__rvm_env_string)"
        rvm_current_rvmrc="$1"
        __rvm_ensure_is_a_function

        source "$1"

      else return $?
      fi
      ;;

    (*/.versions.conf)
      typeset _gem _gem_names _bundle_install
      __rvm_ensure_is_a_function
      rvm_previous_environment="$(__rvm_env_string)"
      rvm_current_rvmrc="$1"

      rvm_ruby_string="$(sed -n '/^ruby=/ {s/ruby=//;p;}' < "$1")"
      [[ -n "${rvm_ruby_string}" ]] || return 2
      rvm_gemset_name="$(sed -n '/^ruby-gemset=/ {s/ruby-gemset=//;p;}' < "$1")"
      rvm_create_flag=1 __rvm_use   || return 3
      # TODO: read env.* # how to sanitize ?

      _gem_names="$(sed -n '/^ruby-gem-install=/ {s/ruby-gem-install=//;p;}' < "$1")"
      for _gem in ${_gem_names//,/ }
      do
        # TODO: add support for versions
        if ! gem list | \grep "^${_gem} " > /dev/null
        then gem install "${_gem}"
        fi
      done

      _bundle_install="$(sed -n '/^ruby-bundle-install=/ {s/ruby-bundle-install=//;p;}' < "$1")"
      if [[ -n "${_bundle_install}" ]] || [[ "${rvm_autoinstall_bundler_flag:-0}" == 1 ]]
      then
        if [[ "${_bundle_install}" == true ]] # prevent file named true for Gemfile
        then __gemfile="$(dirname $1)/Gemfile"

        elif [[ -f "${_bundle_install}" ]]
        then __gemfile="${_bundle_install}"

        elif [[ "${rvm_autoinstall_bundler_flag:-0}" == 1 ]]
        then __gemfile="$(dirname $1)/Gemfile"

        fi
      fi
      ;;

    (*/Gemfile)
      typeset _bundler_version
      __rvm_ensure_is_a_function
      rvm_previous_environment="$(__rvm_env_string)"
      rvm_current_rvmrc="$1"

      rvm_ruby_string="$(sed -n '/^#ruby=/ {s/#ruby=//;p;}' < "$1")"
      [[ -n "${rvm_ruby_string}" ]] || return 2
      rvm_gemset_name="$(sed -n '/^#ruby-gemset=/ {s/#ruby-gemset=//;p;}' < "$1")"
      rvm_create_flag=1 __rvm_use   || return 3

      # TODO: read #env.* # how to sanitize ?

      if [[ "${rvm_autoinstall_bundler_flag:-0}" == "1" ]]
      then
        _bundler_version="$(sed -n '/^#ruby-bundler-version=/ {s/#ruby-bundler-version=//;p;}' < "$1")"
        if ! gem list | \grep "^bundler " | \grep "${_bundler_version}" > /dev/null
        then
          [[ -z "${_bundler_version}" ]] || _bundler_version=" -v ${_bundler_version}"
          gem install "bundler${_bundler_version}"
        fi
        __gemfile="$1"
      fi
      ;;

    (*/.ruby-version|*/.rbfu-version|*/.rbenv-version)
      __rvm_ensure_is_a_function
      rvm_previous_environment="$(__rvm_env_string)"
      rvm_current_rvmrc="$1"

      rvm_ruby_string="$(cat "$1")"
      [[ -n "${rvm_ruby_string}" ]] || return 2
      if [[ -f "$(dirname $1)/.ruby-gemset" ]]
      then
        rvm_gemset_name="$(cat "$(dirname $1)/.ruby-gemset")"
      fi
      rvm_create_flag=1 __rvm_use   || return 3
      # "$(dirname $1)/.rbenv-vars" ... can we support those without licensing ?

      if [[ "${rvm_autoinstall_bundler_flag:-0}" == 1 && -f "$(dirname $1)/Gemfile" ]]
      then
        _bundler_version="$(sed -n '/^#ruby-bundler-version=/ {s/#ruby-bundler-version=//;p;}' < "$1")".strip
        if ! gem list | \grep "^bundler " | \grep "${_bundler_version}" > /dev/null
        then
          [[ -z "${_bundler_version}" ]] || _bundler_version=" -v ${_bundler_version}"
          gem install "bundler${_bundler_version}"
        fi
        __gemfile="$(dirname $1)/Gemfile"
      fi
      ;;

    (*)
      rvm_error "Unsupported file format for '$1'"
      return 1
      ;;
  esac

  if [[ -n "${__gemfile:-}" && -f "${__gemfile:-}" ]]
  then bundle install --gemfile="${__gemfile}" | grep -vE '^Using|Your bundle is complete'
  fi
}

__rvm_project_rvmrc_with_env()
{
  __rvm_do_with_env __rvm_project_rvmrc "$@"
}

__rvm_set_versions_conf()
{
  typeset gemset identifier

  if [[ -s .versions.conf ]]
  then
    mv .versions.conf .versions.conf.$(date +%m.%d.%Y-%H:%M:%S)
    rvm_warn ".version.conf is not empty, moving aside to preserve."
  fi

  identifier=$(__rvm_env_string)
  gemset=${identifier#*@}
  identifier=${identifier%@*}

  printf "%b" "ruby=$identifier
" >> .versions.conf
  if [[ -n "$gemset" && "$gemset" != "$identifier" ]]
  then
    printf "%b" "ruby-gemset=$gemset
" >> .versions.conf
  else
    printf "%b" "#ruby-gemset=my-projectit
" >> .versions.conf
  fi
  printf "%b" "#ruby-gem-install=bundler rake
#ruby-bundle-install=true
" >> .versions.conf
}

__rvm_set_ruby_version()
{
  if [[ -s .ruby-version ]]
  then
    mv .ruby-version .ruby-version.$(date +%m.%d.%Y-%H:%M:%S)
    rvm_warn ".ruby-version is not empty, moving aside to preserve."
  fi

  echo "$(__rvm_env_string)" >> .ruby-version
}

__rvm_set_rvmrc()
{
  typeset flags identifier short_identifier gem_file
  true ${rvm_verbose_flag:=0}

  if [[ "$HOME" != "$PWD" ]]
  then
    if (( rvm_verbose_flag ))
    then
      flags="use "
    fi

    if [[ -s .rvmrc ]]
    then
      mv .rvmrc .rvmrc.$(date +%m.%d.%Y-%H:%M:%S)
      rvm_warn ".rvmrc is not empty, moving aside to preserve."
    fi

    identifier=$(__rvm_env_string)
    short_identifier="${identifier#ruby-}"
    short_identifier="${short_identifier%%-*}"

    printf "%b" "#!/usr/bin/env bash

# This is an RVM Project .rvmrc file, used to automatically load the ruby
# development environment upon cd'ing into the directory

# First we specify our desired <ruby>[@<gemset>], the @gemset name is optional,
# Only full ruby name is supported here, for short names use:
#     echo \"rvm use ${short_identifier}\" > .rvmrc
environment_id=\"$identifier\"

# Uncomment the following lines if you want to verify rvm version per project
# rvmrc_rvm_version=\"${rvm_version}\" # 1.10.1 seams as a safe start
# eval \"\$(echo \${rvm_version}.\${rvmrc_rvm_version} | awk -F. '{print \"[[ \"\$1*65536+\$2*256+\$3\" -ge \"\$4*65536+\$5*256+\$6\" ]]\"}' )\" || {
#   echo \"This .rvmrc file requires at least RVM \${rvmrc_rvm_version}, aborting loading.\"
#   return 1
# }
" >> .rvmrc
    if [[ "$identifier" =~ jruby* ]]
    then
      printf "%b" "
# Uncomment following line if you want options to be set only for given project.
# PROJECT_JRUBY_OPTS=( --1.9 )
# The variable PROJECT_JRUBY_OPTS requires the following to be run in shell:
#    chmod +x \${rvm_path}/hooks/after_use_jruby_opts
" >> .rvmrc
    fi
    printf "%b" "
# First we attempt to load the desired environment directly from the environment
# file. This is very fast and efficient compared to running through the entire
# CLI and selector. If you want feedback on which environment was used then
# insert the word 'use' after --create as this triggers verbose mode.
if [[ -d \"\${rvm_path:-\$HOME/.rvm}/environments\"
  && -s \"\${rvm_path:-\$HOME/.rvm}/environments/\$environment_id\" ]]
then
  \\. \"\${rvm_path:-\$HOME/.rvm}/environments/\$environment_id\"
  [[ -s \"\${rvm_path:-\$HOME/.rvm}/hooks/after_use\" ]] &&
    \\. \"\${rvm_path:-\$HOME/.rvm}/hooks/after_use\" || true
" >> .rvmrc
    if [[ " $flags " =~ " use " ]]
    then
      printf "%b" "  if [[ \$- == *i* ]] # check for interactive shells
  then echo \"Using: \$(tput setaf 2)\$GEM_HOME\$(tput sgr0)\" # show the user the ruby and gemset they are using in green
  else echo \"Using: \$GEM_HOME\" # don't use colors in non-interactive shells
  fi
" >> .rvmrc
    fi
    printf "%b" "else
  # If the environment file has not yet been created, use the RVM CLI to select.
  rvm --create $flags \"\$environment_id\" || {
    echo \"Failed to create RVM environment '\${environment_id}'.\"
    return 1
  }
fi
" >> .rvmrc
    for gem_file in *.gems
    do
      case "$gem_file" in
        (\*.gems) continue ;;
      esac
      printf "%b" "
# If you use an RVM gemset file to install a list of gems (*.gems), you can have
# it be automatically loaded. Uncomment the following and adjust the filename if
# necessary.
#
# filename=\".gems\"
# if [[ -s \"\$filename\" ]]
# then
#   rvm gemset import \"\$filename\" | grep -v already | grep -v listed | grep -v complete | sed '/^$/d'
# fi
" >> .rvmrc
    done
    if [[ -s Gemfile ]]
    then
      printf "%b" "
# If you use bundler, this might be useful to you:
# if [[ -s Gemfile ]] && {
#   ! builtin command -v bundle >/dev/null ||
#   builtin command -v bundle | grep \$rvm_path/bin/bundle >/dev/null
# }
# then
#   printf \"%b\" \"The rubygem 'bundler' is not installed. Installing it now.\\\\n\"
#   gem install bundler
# fi
# if [[ -s Gemfile ]] && builtin command -v bundle >/dev/null
# then
#   bundle install | grep -vE '^Using|Your bundle is complete'
# fi
" >> .rvmrc
    fi
  else
    rvm_error ".rvmrc cannot be set in your home directory.\
      \nThe home .rvmrc is for global rvm settings only."
  fi
}

__rvm_project_dir_check()
{
  [[ -n "${1:-}" && -d "$1" ]] && {
    [[ -f "$1/.rvmrc"         && -s "$1/.rvmrc"         ]] ||
    [[ -f "$1/.versions.conf" && -s "$1/.versions.conf" ]] ||
    [[ -f "$1/.ruby-version"  && -s "$1/.ruby-version"  ]] ||
    [[ -f "$1/.rbfu-version"  && -s "$1/.rbfu-version"  ]] ||
    [[ -f "$1/.rbenv-version" && -s "$1/.rbenv-version" ]] ||
    {
      [[ -f "$1/Gemfile" && -s "$1/Gemfile" ]] &&
      \grep "^#ruby=" "$1/Gemfile" >/dev/null
    }
  }
}
