#!/usr/bin/env bash

# Drop in replacement for sed -i compatible with OpenBSD
# Assumes that filename is the first argument, all others are passed onto sed

__rvm_sed_i()
{
    typeset filename
    filename="$1"
    shift

    sed "$@" < "${filename}" > "${filename}.new"
    mv "${filename}.new" "${filename}"
}
