#!/usr/bin/env bash

if [[ -z "${rvm_tar_command:-}" ]]
then
  # check for the right tar to use
  if builtin command -v gtar >/dev/null
  then rvm_tar_command=gtar
  else rvm_tar_command=tar
  fi
fi

if
  [[ ! " ${rvm_tar_options:-} " =~ " --no-same-owner "  ]] &&
  # pre-gnu
  $rvm_tar_command --help 2>&1 | GREP_OPTIONS="" \grep -- --no-same-owner >/dev/null
then
  rvm_tar_options="${rvm_tar_options:-}${rvm_tar_options:+ }--no-same-owner"
fi

# Functions RVM is built on
# __rvm_string_match <value> <string|glob>
if
 [[ -n "$ZSH_VERSION" ]]
then
  __rvm_string_match()
  {
    typeset _string
    _string="$1"
    shift
    while (( $# ))
    do
      eval "\
      case \"\${_string}\" in\
        ($1) return 0 ;;\
      esac\
      "
      shift
    done
    return 1
  }
else
  __rvm_string_match()
  {
    typeset _string
    _string="$1"
    shift
    while (( $# ))
    do
      case "${_string}" in
        ($1) return 0 ;;
      esac
      shift
    done
    return 1
  }
fi

__rvm_array_contains()
{
  typeset _search _iterator
  _search="$1"
  shift
  for _iterator
  do
    case "${_iterator}" in
      (${_search}) return 0 ;;
    esac
  done
  return 1
}

__rvm_array_add_or_update()
{
  typeset _array_name _variable _separator _value _local_value
  typeset -a _array_value_old _array_value_new

  _array_name="$1"
  _variable="$2"
  _separator="$3"
  _value="${4##${_separator}}"
  _array_value_new=()
  eval "_array_value_old=( \"\${${_array_name}[@]}\" )"

  case " ${_array_value_old[*]} " in
    (*[[:space:]]${_variable}*)
      for _local_value in "${_array_value_old[@]}"
      do
        case "${_local_value}" in
          (${_variable}*)
            _array_value_new+=( "${_local_value}${_separator}${_value}" )
            ;;
          (*)
            _array_value_new+=( "${_local_value}" )
            ;;
        esac
      done
      ;;
    (*)
      _array_value_new=( "${_array_value_old[@]}" "${_variable}${_value}" )
      ;;
  esac

  eval "${_array_name}=( \"\${_array_value_new[@]}\" )"
}

__rvm_array_prepend_or_ignore()
{
  typeset _array_name _variable _separator _value _local_value
  typeset -a _array_value_old _array_value_new

  _array_name="$1"
  _variable="$2"
  _separator="$3"
  _value="$4"
  _array_value_new=()
  eval "_array_value_old=( \"\${${_array_name}[@]}\" )"

  case " ${_array_value_old[*]} " in
    (*[[:space:]]${_variable}*)
      for _local_value in "${_array_value_old[@]}"
      do
        case "${_local_value}" in
          (${_variable}*)
            rvm_debug "__rvm_array_prepend_or_ignore ${_array_name} ${_variable}\"${_value}${_separator}${_local_value#${_variable}}\""
            _array_value_new+=( "${_variable}${_value}${_separator}${_local_value#${_variable}}" )
            ;;
          (*)
            _array_value_new+=( "${_local_value}" )
            ;;
        esac
      done
      eval "${_array_name}=( \"\${_array_value_new[@]}\" )"
      ;;
  esac
}

# Drop in replacement for sed -i compatible with OpenBSD
# Assumes that filename is the first argument, all others are passed onto sed
__rvm_sed_i()
{
  typeset _filename _executable
  [[ -n "${1:-}" ]] || {
    rvm_debug "no file given for __rvm_sed_i"
    return 0
  }
  _filename="$1"
  shift

  if [[ -x "${_filename}" ]]
  then _executable=true
  fi

  {
    __rvm_sed "$@" < "${_filename}" > "${_filename}.new" &&
    \mv -f "${_filename}.new" "${_filename}"
  } 2>&1 | rvm_debug_stream

  if [[ -n "${_executable:-}" ]]
  then chmod +x "${_filename}"
  fi
}

# Drop in cd which _desotn't_ respect cdpath
__rvm_cd()
{
    typeset old_cdpath ret
    ret=0
    old_cdpath="${CDPATH}"
    CDPATH="."
    chpwd_functions="" builtin cd "$@" || ret=$?
    CDPATH="${old_cdpath}"
    return $ret
}

# Drop in replacement for which compatible with OSX / Zsh
__rvm_which()
{
  if command which --skip-alias --skip-functions which >/dev/null 2>&1
  then command which --skip-alias --skip-functions "$@"
  elif command whence whence >/dev/null 2>&1
  then command whence -p "$@"
  elif command which which >/dev/null 2>&1
  then command which "$@"
  elif which which >/dev/null 2>&1
  then which "$@"
  else return 1
  fi
}

gnu_utils=( awk find sed make tail )

case "$(uname)" in
  (SunOS)
    case "$(uname -v)" in
      (*joyent*) gnu_tools_path=/opt/local/bin ;;
      (*)        gnu_tools_path=/usr/gnu/bin   ;;
    esac
    [[ -x $gnu_tools_path/grep ]] ||
      rvm_error "ERROR: Missing GNU grep. Make sure it is installed in $gnu_tools_path/grep before using RVM!"
    eval "__rvm_grep() { GREP_OPTIONS=\"\" $gnu_tools_path/grep \"\$@\" || return \$?; }"

    for gnu_util in "${gnu_utils[@]}"
    do
      [[ -x $gnu_tools_path/$gnu_util ]] ||
        rvm_error "ERROR: Missing GNU $gnu_util. Make sure it is installed in $gnu_tools_path/$gnu_util before using RVM!"
      eval "__rvm_$gnu_util() { $gnu_tools_path/$gnu_util \"\$@\" || return \$?; }"
    done
    ;;
  (*)
    __rvm_grep()
    {
      GREP_OPTIONS="" \grep "$@" || return $?
    }

    for gnu_util in "${gnu_utils[@]}"
    do
      eval "__rvm_$gnu_util() { \\$gnu_util \"\$@\" || return \$?; }"
    done
    ;;
esac

unset gnu_tools_path gnu_util gnu_utils

## duplication marker 32fosjfjsznkjneuera48jae
__rvm_curl_output_control()
{
  if
    (( ${rvm_quiet_curl_flag:-0} == 1 ))
  then
    __flags+=( "--silent" "--show-error" )
  elif
    [[ " $*" =~ " -s" || " $*" =~ " --silent" ]]
  then
    # make sure --show-error is used with --silent
    [[ " $*" =~ " -S" || " $*" =~ " -sS" || " $*" =~ " --show-error" ]] ||
    {
      __flags+=( "--show-error" )
    }
  fi
}

## duplication marker 32fosjfjsznkjneuera48jae
# -S is automatically added to -s
__rvm_curl()
(
  __rvm_which curl >/dev/null ||
  {
    rvm_error "RVM requires 'curl'. Install 'curl' first and try again."
    return 200
  }

  typeset -a __flags
  __flags=( --fail --location --max-redirs 10 )

  if [[ -n "${rvm_proxy:-}" ]]
  then __flags+=( --proxy "${rvm_proxy:-}" )
  fi

  __rvm_curl_output_control

  unset curl
  __rvm_debug_command \curl "${__flags[@]}" "$@" || return $?
)

is_a_function()
{
  typeset -f $1 >/dev/null 2>&1 || return $?
}

is_parent_of()
{
  typeset name pid ppid pname
  name=$1
  pid=$2
  while [[ -n "$pid" && "$pid" != "0" ]]
  do
    read ppid pname < <(ps -p $pid -o ppid= -o comm=)
    if [[ -n "$ppid" && -n "$pname" ]]
    then
      if [[ "$pname" == "$name" ]]
      then
        echo $pid
        return 0
      else
        pid=$ppid
      fi
    else
      break
    fi
  done
  return 1
}

__rvm_string_includes()
{
  typeset __search __text="$1"
  shift
  for __search in "$@"
  do
    if [[ " ${__text} " =~ " ${__search} " ]]
    then return 0
    fi
  done
  return 1
}

__function_on_stack()
{
  __rvm_string_includes "${FUNCNAME[*]}" "$@" || return $?
}

# read lines from file / stdin(-)
__rvm_read_lines()
{
  typeset IFS
  # NEW LINE, BE CAREFUL
  IFS="
"
  if [[ "${2:--}" == "-" ]]
  then eval "$1=( \$( \cat - ) )"
  else eval "$1=( \$( \cat \"\${2:--}\" ) )"
  fi
}

__rvm_ruby_config_save()
{
  typeset ruby_path config_path default_config_path
  ruby_path="${1:-$rvm_ruby_home/bin/ruby}"
  default_config_path="#{RbConfig::CONFIG[\"prefix\"]}/config"
  config_path="${2:-$default_config_path}"
  "$ruby_path" -rrbconfig -e '\
    File.open("'"$config_path"'","w") { |file|
      RbConfig::CONFIG.sort.each{|key,value|
        file.write("#{key.gsub(/\.|-/,"_")}=\"#{value.gsub("$","\\$")}\"\n")
      }
    }
  ' >/dev/null 2>&1
}

__rvm_record_ruby_configs()
{
  for dir in "$rvm_path/rubies/"*
  do
    if
      [[ ! -L "${dir}" && ! -s "${dir}/config" && -x "${dir}/bin/ruby" ]]
    then
      __rvm_ruby_config_save "${dir}/bin/ruby" ||
      {
        typeset string="${dir##*/}"
        rvm_error "    Can not save config data for ruby: '${string}', most likely it is broken installation and you can:
    - try fix it: 'rvm reinstall ${string}', OR:
    - remove  it: 'rvm uninstall ${string} --gems'"
      }
    fi
  done
}
