#!/usr/bin/env bash

tools_strings()
{
  \typeset __ruby_name
  for __ruby_name in "$@"
  do
    if
      __rvm_select "$__ruby_name" 1>&2
    then
      echo "${rvm_ruby_gem_home##*/}"
    else
      : status:$?
      echo ""
    fi
    __rvm_unset_ruby_variables
  done
}
