#!/usr/bin/env bash

__rvm_version()
{
  echo "rvm $(__rvm_version_installed) by $(__rvm_version_authors) [$(__rvm_version_website)]"
}

__rvm_version_website()
{
  echo "https://rvm.io"
}

__rvm_version_authors()
{
  echo "Michal Papis, Piotr Kuczynski, Wayne E. Seguin"
}

__rvm_version_copyright()
{
  echo "(c) 2009-2017 $(__rvm_version_authors)"
}

__rvm_print_headline()
{
  rvm_log "Ruby enVironment Manager ${rvm_version} $(__rvm_version_copyright)
"
}

__rvm_version_remote()
{
  __rvm_curl -s --max-time 10 https://github.com/rvm/rvm/raw/stable/VERSION || true
}

__rvm_version_installed()
{
  echo "$(\command \cat "$rvm_path/VERSION") ($(\command \cat "$rvm_path/RELEASE" 2>/dev/null))"
}
