#!/usr/bin/env bash

function remove_binstubs_from_path()
{
  if
    [[ -n "$1" ]]
  then
    export PATH
    PATH=":${PATH}:"
    PATH="${PATH//:$1:/:}"
    PATH="${PATH//::/:}"
    PATH="${PATH#:}"
    PATH="${PATH%:}"
  fi
}
