#!/usr/bin/env bash

jruby_ngserver_is_running()
{
  ps auxww | grep -q '[s]un.java.command=com.martiansoftware.nailgun.NGServer'
}

jruby()
{
  if jruby_ngserver_is_running
  then
    command jruby --ng "$@"
  else
    command jruby "$@"
  fi
}

ruby()
{
  jruby "$@"
}

