#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_deepin_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_deepin_define_libreadline()
{
  requirements_check libreadline-dev
}

requirements_deepin_define_libssl()
{
  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*)
        # legacy libssl-dev required by older version of ruby has been renamed to libssl1.0-dev
        undesired_check libssl-dev
        requirements_check libssl1.0-dev
      ;;

    (*)
      undesired_check libssl1.0-dev
      requirements_check libssl-dev
      ;;
  esac
}

requirements_deepin_define_clang_llvm()
{
  requirements_check clang-3.6 llvm-3.6 llvm-3.6-dev
  rvm_configure_flags+=( --cc=clang-3.6 --cxx=clang++-3.6 --llvm-config=llvm-config-3.6)
}

requirements_deepin_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
