#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_devuan_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_devuan_define_libreadline()
{
  requirements_check libreadline6-dev
}

requirements_devuan_define_libssl()
{
  requirements_check libssl-dev
}

requirements_devuan_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
