#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_elementary_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_elementary_define_libreadline()
{
  requirements_check libreadline6-dev
}

requirements_elementary_define_libssl()
{
  if __rvm_version_compare "${_system_version}" -ge 5
  then
    # libssl1.0-dev is available starting from Debian 9 (Stretch)
    requirements_debian_define_base libssl1.0-dev
  else
    requirements_debian_define_base libssl-dev
  fi
}

requirements_elementary_define_clang_llvm()
{
  requirements_check clang-3.6 llvm-3.6 llvm-3.6-dev
  rvm_configure_flags+=( --cc=clang-3.6 --cxx=clang++-3.6 --llvm-config=llvm-config-3.6)
}


requirements_elementary_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
