#!/usr/bin/env bash

if
  __rvm_version_compare "${_system_version}" -ge 22
then
  source "$rvm_scripts_path/functions/requirements/fedora_dnf"
else
  source "$rvm_scripts_path/functions/requirements/fedora_yum"
fi
