#!/usr/bin/env bash

requirements_fedora_define_openssl()
{
  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*|ruby-1.8*)
      if
        __rvm_version_compare "${_system_version}" -ge 26
      then
        undesired_check openssl-devel
        requirements_check compat-openssl10-devel
      else
        undesired_check compat-openssl10-devel
        requirements_check openssl-devel
      fi
      ;;

    (*)
      undesired_check compat-openssl10-devel
      requirements_check openssl-devel
      ;;
  esac
}

requirements_fedora_define_glibc()
{
  if
    __rvm_version_compare "${_system_version}" -lt 33
  then
    requirements_check glibc-headers glibc-devel
  else
    requirements_check glibc-devel
  fi
}

if
  __rvm_which dnf >/dev/null 2>&1 # should be true for Fedora 22+
then
  source "$rvm_scripts_path/functions/requirements/fedora_dnf"
else
  source "$rvm_scripts_path/functions/requirements/fedora_yum"
fi
