#!/usr/bin/env bash

# old handlers before pkgng
requirements_freebsd_lib_installed()
{
  pkg_info | \grep "^$1" >/dev/null 2>&1 || return $?
}

requirements_freebsd_libs_install()
{
  __rvm_try_sudo pkg_add -r "$@" || return $?
}

# new handlers for pkgng
requirements_freebsd_pkgng_lib_installed()
{
  pkg info | \grep "^$1" >/dev/null 2>&1 || return $?
}

requirements_freebsd_pkgng_libs_install()
{
  __rvm_try_sudo pkg install "$@" || return $?
}

requirements_freebsd_install_node()
{
  __rvm_try_sudo make -C /usr/ports/www/node install clean || return $?
}

requirements_freebsd_before()
{
  # Test if we already have ports. If not, get it. If so, update it
  [[ -d /usr/ports ]] ||
  {
    rvm_requiremnts_fail_or_run_action 2 \
      "Skipping portsnap fetch extract, make sure your system is up to date." \
      __rvm_try_sudo portsnap fetch extract || return $?
    packages_flags+=( "portsnap-extracted" )
  }
  __rvm_which pkg >/dev/null ||
  {
    rvm_requiremnts_fail_or_run_action 3 \
      "Skipping pkgng bootstrap, make sure your system is up to date." \
      requirements_freebsd_bootstrap_pkgng || return $?
  }
  __lib_type="freebsd"
  if __rvm_which pkg >/dev/null
  then __lib_type+='_pkgng'
  fi
}

requirements_freebsd_bootstrap_pkgng()
{
  # pkgng should work fine on FreeBSD 8.0+ upwards
  # The bootstrapper is natively available in 9.1+
  if
    __rvm_version_compare "$_system_version" -ge 9.1
  then
    __rvm_try_sudo /usr/sbin/pkg || return $?
  else
    __rvm_try_sudo make -C /usr/ports/ports-mgmt/pkg install clean || return $?
  fi
}

requirements_freebsd_update_system()
{
  # Test if we already have ports. If not, get it. If so, update it
  [[ " ${packages_flags[*]} " =~ " portsnap-extracted " ]] ||
    __rvm_try_sudo portnsap fetch update  || return $?
}

requirements_freebsd_define()
{
  case "$1" in
    (update-system)
      true
      ;;
    (rvm)
      requirements_check bash curl
      ;;
    (jruby*head)
      requirements_check jdk apache-ant git
      ;;
    (jruby*)
      requirements_check jdk
      ;;
    (ir*)
      requirements_check mono
      ;;
    (opal)
      __rvm_which node >/dev/null || packages_custom+=( node )
      ;;
    (*-head)
      # OpenSSL is installed by default http://www.freebsd.org/crypto.html
      requirements_check gcc-4 autotools-2 libtool bison readline-6 libxslt-1 libyaml-0 sqlite3 gdbm git
      __rvm_update_configure_opt_dir "$1" "/usr/local"
      ;;
    (*)
      # OpenSSL is installed by default http://www.freebsd.org/crypto.html
      requirements_check gcc-4 autotools-2 libtool bison readline-6 libxslt-1 libyaml-0 sqlite3 gdbm
      __rvm_update_configure_opt_dir "$1" "/usr/local"
      ;;
  esac
}
