#!/usr/bin/env bash

requirements_find_gentoo_pkgcore()
{
  if
    eselect package-manager >/dev/null 2>&1
  then
    [[ $(eselect package-manager show | __rvm_tail -1 | __rvm_sed 's/ //g') = 'pkgcore' ]] || return $?
  else
    __rvm_which pmerge >/dev/null 2>&1 || return $?
  fi
}

requirements_gentoo_pkgcore_lib_installed()
{
  pquery --vdb "$1" | __rvm_grep "$1" >/dev/null || return $?
}

requirements_gentoo_pkgcore_libs_install()
{
  __rvm_try_sudo pmerge "$@" || return $?
}

requirements_gentoo_pkgcore_update_system()
{
  __rvm_try_sudo pmaint sync || return $?
}
