#!/usr/bin/env bash

requirements_find_gentoo_portage()
{
  if eselect package-manager >/dev/null 2>&1
  then
    if [[ $(eselect package-manager show | tail -1 | sed 's/ //g') = 'portage' ]] || [[ $(eselect package-manager show | tail -1 | sed 's/ //g') = '(none)' ]]
    then
      return 0
    else
      return 1
    fi
  else
    if which emerge >/dev/null 2>&1
    then
      return 0
    else
      return 1
    fi
  fi
}

requirements_find_gentoo_paludis()
{
  if eselect package-manager >/dev/null 2>&1
  then
    if [[ $(eselect package-manager show | tail -1 | sed 's/ //g') = 'paludis' ]]
    then
      return 0
    else
      return 1
    fi
  else
    if which cave >/dev/null 2>&1
    then
      return 0
    else
      return 1
    fi
  fi
}

requirements_find_gentoo_pkgcore()
{
  if eselect package-manager >/dev/null 2>&1
  then
    if [[ $(eselect package-manager show | tail -1 | sed 's/ //g') = 'pkgcore' ]]
    then
      return 0
    else
      return 1
    fi
  else
    if which pmerge >/dev/null 2>&1
    then
      return 0
    else
      return 1
    fi
  fi
}

requirements_gentoo()
{
  typeset __type
  for __type in gentoo_portage gentoo_paludis gentoo_pkgcore
  do
    if
      requirements_find_${__type}
    then
      __rvm_requirements_run ${__type} "$@" || return $?
      return 0
    fi
  done

  # fallback
  __rvm_requirements_run gentoo_portage "$@" || return $?
}
