#!/usr/bin/env bash

requirements_gentoo_portage_lib_installed() [[ -n "$(portageq match / "$1" 2>/dev/null)" ]]

requirements_gentoo_portage_libs_install()
{
  __rvm_try_sudo emerge "$@" || return $?
}

requirements_gentoo_portage_ensure_libs()
{
  typeset -a packages_installed packages_missing packages_to_install
  __rvm_filter_installed_packages gentoo_portage "$@" || return $?
}

requirements_gentoo_portage_run()
{
  case "$1" in
    (update-system)
      rvm_requiremnts_fail_or_run_action 3 \
        "Skipping \`emerge --sync\` make sure your system is up to date." \
        __rvm_try_sudo emerge --sync || return $?
      ;;
    (rvm)
      requirements_gentoo_portage_ensure_libs net-misc/curl sys-devel/patch app-shells/bash
      ;;
    (jruby*head)
      requirements_gentoo_portage_ensure_libs dev-java/sun-jdk dev-java/sun-jre-bin dev-vcs/git
      ;;
    (jruby*)
      requirements_gentoo_portage_ensure_libs dev-java/sun-jdk dev-java/sun-jre-bin
      ;;
    (ir*)
      requirements_gentoo_portage_ensure_libs dev-lang/mono
      ;;
    (opal)
      requirements_gentoo_portage_ensure_libs net-libs/nodejs
      ;;
    (*-head)
      requirements_gentoo_portage_ensure_libs virtual/libiconv sys-libs/readline sys-libs/zlib dev-libs/openssl net-misc/curl dev-libs/libyaml dev-db/sqlite dev-libs/libxslt sys-devel/libtool sys-devel/gcc sys-devel/autoconf sys-devel/automake sys-devel/bison sys-devel/m4 dev-vcs/git
      ;;
    (*)
      requirements_gentoo_portage_ensure_libs virtual/libiconv sys-libs/readline sys-libs/zlib dev-libs/openssl net-misc/curl dev-libs/libyaml dev-db/sqlite dev-libs/libxslt sys-devel/libtool sys-devel/gcc sys-devel/autoconf sys-devel/automake sys-devel/bison sys-devel/m4
      ;;
  esac
}
