#!/usr/bin/env bash

requirements_gentoo_paludis_lib_installed()
{
  cave show "$1" | grep "::installed" >/dev/null || return $?
}

requirements_gentoo_paludis_libs_install()
{
  __rvm_try_sudo cave resolve -x "$@" || return $?
}

requirements_gentoo_paludis_ensure_libs()
{
  typeset -a packages_installed packages_missing packages_to_install
  __rvm_filter_installed_packages gentoo_paludis "$@" || return $?
}

requirements_gentoo_paludis_run()
{
  case "$1" in
    (update-system)
      rvm_requiremnts_fail_or_run_action 3 \
        "Skipping \`cave sync\` make sure your system is up to date." \
        __rvm_try_sudo cave sync || return $?
      ;;
    (rvm)
      requirements_gentoo_paludis_ensure_libs net-misc/curl sys-devel/patch app-shells/bash
      ;;
    (jruby*head)
      requirements_gentoo_paludis_ensure_libs dev-java/sun-jdk dev-java/sun-jre-bin dev-vcs/git
      ;;
    (jruby*)
      requirements_gentoo_paludis_ensure_libs dev-java/sun-jdk dev-java/sun-jre-bin
      ;;
    (ir*)
      requirements_gentoo_paludis_ensure_libs dev-lang/mono
      ;;
    (opal)
      requirements_gentoo_paludis_ensure_libs net-libs/nodejs
      ;;
    (*-head)
      requirements_gentoo_paludis_ensure_libs virtual/libiconv sys-libs/readline sys-libs/zlib dev-libs/openssl net-misc/curl dev-vcs/git dev-libs/libyaml dev-db/sqlite dev-libs/libxslt sys-devel/libtool sys-devel/gcc sys-devel/autoconf sys-devel/automake sys-devel/bison sys-devel/m4
      ;;
    (*)
      requirements_gentoo_paludis_ensure_libs virtual/libiconv sys-libs/readline sys-libs/zlib dev-libs/openssl net-misc/curl dev-vcs/git dev-libs/libyaml dev-db/sqlite dev-libs/libxslt sys-devel/libtool sys-devel/gcc sys-devel/autoconf sys-devel/automake sys-devel/bison sys-devel/m4
      ;;
  esac
}
