#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/centos"

requirements_mageia_define_glibc()
{
  requirements_check glibc-devel
}

requirements_mageia_define_libyaml()
{
  if
    [[ "${_system_arch}" == "x86_64" ]]
  then
    requirements_check lib64yaml-devel
  else
    requirements_check libyaml-devel
  fi
}

requirements_mageia_define_openssl()
{
  requirements_check openssl-devel
}

requirements_mageia_define()
{
  __lib_type=centos

  requirements_centos_define "$@"
}
