#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_mint_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_mint_define_libreadline()
{
  requirements_check libreadline-dev
}

requirements_mint_define_libssl()
{
  # Legacy libssl-dev required by older version of ruby has been renamed to libssl1.0-dev
  # starting from Mint 19 (Tara)

  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*)
      if
        __rvm_version_compare ${_system_version} -ge 19
      then
        undesired_check libssl-dev
        requirements_check libssl1.0-dev
      else
        requirements_check libssl-dev
      fi
      ;;

    (*)
      requirements_check libssl-dev
      ;;
  esac

  requirements_check libssl-dev
}

requirements_mint_define_clang_llvm()
{
  if
    __rvm_version_compare ${_system_version} -ge 19.1
  then
    requirements_check clang-3.9 llvm-3.9 llvm-3.9-dev
    rvm_configure_flags+=( --cc=clang-3.9 --cxx=clang++-3.9 --llvm-config=llvm-config-3.9)
  else
    requirements_check clang-3.6 llvm-3.6 llvm-3.6-dev
    rvm_configure_flags+=( --cc=clang-3.6 --cxx=clang++-3.6 --llvm-config=llvm-config-3.6)
  fi
}

requirements_mint_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
