#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_mint_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_mint_define_libreadline()
{
  requirements_check libreadline6-dev
}

requirements_mint_define_libssl()
{
  requirements_check libssl-dev
}

requirements_mint_define_clang_llvm()
{
  requirements_check clang-3.5 llvm-3.5 llvm-3.5-dev
}

requirements_mint_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
