#!/usr/bin/env bash

requirements_netbsd_lib_installed()
{
  [[ -f /etc/mtree/set.$1 ]] || return $?
}

requirements_netbsd_libs_install()
{
  _set_base_url="http://ftp.netbsd.org/pub/NetBSD/NetBSD-${_system_version}/${_system_arch/x86_64/amd64}/binary/sets"
  for _set in "$@"
  do
    _set_url="${_set_base_url}/${_set}.tgz"
    _set_md5=$(__rvm_curl -s ${_set_base_url}/MD5 | grep "(${_set}.tgz)" | __rvm_awk '{print $NF}')
    __rvm_curl ${_set_url} -o ${rvm_archives_path}/${_set}.tgz || return $?
    #TODO: echo error into log file
    [[ $(__rvm_md5_calculate ${rvm_archives_path}/${_set}.tgz) == ${_set_md5} ]] || return $?
    __rvm_try_sudo tar xzf ${rvm_archives_path}/${_set}.tgz -C / || return $?
  done
  unset _set _set_url _set_md5
}

requirements_netbsd_check_custom()
{
  for lib in "$@"
  do
    [[ " ${packages_custom[*]} " =~ " $lib " ]] ||
    requirements_netbsd_custom_lib_installed "$lib" || packages_custom+=( "$lib" )
  done
  unset lib
}

requirements_netbsd_custom_lib_installed()
{
  pkg_info -qE "$1" || return $?
}

requirements_netbsd_install_custom()
{
  #TODO: This is unreliable as won't work with versions > 9
  __rvm_try_sudo \
    PKG_PATH="http://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/${_system_version:0:3}/All/" \
    pkg_add "$@" || return $?
}

requirements_netbsd_custom_after()
{
  _certs=$(ls /etc/openssl/certs)
  [[ ! -n "${certs}" && -f /etc/ssl/certs/ca-certificates.crt ]] ||
    __rvm_try_sudo mozilla-rootcerts install >/dev/null 2>&1 || return $?
}

requirements_netbsd_define()
{
  case "$1" in
    (rvm)
      requirements_netbsd_check_custom bash curl mozilla-rootcerts p5-Digest-SHA
      ;;
    (jruby*head)
      true
      ;;
    (jruby*)
      requirements_netbsd_check_custom openjdk7
      ;;
    (ir*)
      true
      ;;
    (opal)
      true
      ;;
    (*-head)
      requirements_check comp
      requirements_netbsd_check_custom automake autoconf libtool bison gdbm libffi libyaml scmgit
      __rvm_update_configure_opt_dir "$1" "/usr/pkg"
      ;;
    (*)
      requirements_check comp
      requirements_netbsd_check_custom automake autoconf libtool bison gdbm libffi libyaml
      __rvm_update_configure_opt_dir "$1" "/usr/pkg"
      ;;
  esac
}
