#!/usr/bin/env bash

requirements_openbsd_lib_installed()
{
  pkg_info | \grep "^$1" >/dev/null 2>&1 || return $?
}

requirements_openbsd_libs_install()
{
  __rvm_try_sudo pkg_add -z "$@" || return $?
}

requirements_openbsd_ensure_libs()
{
  typeset -a packages_installed packages_missing packages_to_install
  __rvm_filter_installed_packages openbsd "$@" || return $?
}

requirements_openbsd_run()
{
  case "$1" in
    (update-system)
      [[ -d /usr/ports ]] ||
        curl ftp://ftp.openbsd.org/pub/OpenBSD/$(uname -r)/ports.tar.gz | __rvm_try_sudo tar -C /usr -zx
      ;;
    (rvm)
      requirements_openbsd_ensure_libs bash curl git
      ;;
    (jruby-head*)
      requirements_openbsd_ensure_libs jdk apache-ant
      ;;
    (jruby*)
      requirements_openbsd_ensure_libs jdk
      ;;
    (ir*)
      requirements_openbsd_ensure_libs mono
      ;;
    (opal)
      __rvm_try_sudo make -C /usr/ports/www/node install clean
      ;;
    (*)
      # OpenSSL is installed by default http://www.openbsd.org/crypto.html
      requirements_openbsd_ensure_libs gcc-4 autoconf-2 automake-1 libtool bison readline-6 libxslt-1 libyaml-0
      __rvm_update_configure_opt_dir "$1" "/usr/local"
      ;;
  esac
}
