#!/usr/bin/env bash

set -e

function requirements_zypper()
{
  typeset -a command_to_run command_flags
  command_to_run=()
  command_flags=()

  while
    (( $# ))
  do
    case "$1" in
      (echo)
        command_to_run+=( $1 )
        shift
        ;;
      (run)
        shift
        ;;
      (force)
        command_flags+=( -y )
        shift
        ;;
      (*)
        break
        ;;
    esac
  done

  (( UID == 0 )) || command_to_run+=( sudo )

  while
    (( $# ))
  do
    case "$1" in
      (update-system)
        true
        ;;
      (rvm)
        "${command_to_run[@]}" zypper install "${command_flags[@]}" bash curl git patch
        ;;
      (jruby*)
        "${command_to_run[@]}" zypper install "${command_flags[@]}" java
        ;;
      (ir*)
        "${command_to_run[@]}" zypper install "${command_flags[@]}" mono
        ;;
      (opal)
        "${command_to_run[@]}" zypper install "${command_flags[@]}" nodejs
        ;;
      (*)
        "${command_to_run[@]}" zypper install "${command_flags[@]}" patterns-openSUSE-devel_basis gcc-c++ bzip2 readline-devel zlib-devel libxml2-devel libxslt-devel libyaml-devel libopenssl-devel libffi-devel libtool bison
        ;;
    esac
    shift
  done
}

requirements_zypper "$@"
