#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/openmandriva_dnf"
source "$rvm_scripts_path/functions/requirements/openmandriva_old"

requirements_openmandriva_before()
{
  \typeset __type
  for __type in openmandriva_old openmandriva_dnf
  do
    if
      requirements_find_${__type}
    then
      __lib_type=${__type}
      return 0
    fi
  done

  # fallback
  __lib_type=openmandriva_old
}
