#!/usr/bin/env bash

requirements_openindiana_lib_installed()
{
  pkg info "$1" > /dev/null || return $?
}

requirements_openindiana_libs_install()
{
  __rvm_try_sudo pkg install "$@" || return $?
}

requirements_openindiana_ensure_libs()
{
  typeset -a packages_installed packages_missing packages_to_install
  __rvm_filter_installed_packages openindiana "$@" || return $?
}

requirements_openindiana_run()
{
  case "$1" in
    (update-system)
      true
      ;;
    (rvm)
      requirements_openindiana_ensure_libs bash curl git text/gnu-patch
      ;;
    (jruby-head*)
      requirements_openindiana_ensure_libs jdk apache-ant
      ;;
    (jruby*)
      requirements_openindiana_ensure_libs jdk
      ;;
    (ir*)
      requirements_openindiana_ensure_libs mono
      ;;
    (opal)
      requirements_openindiana_ensure_libs runtime/javascript/nodejs
      ;;
    (*)
      requirements_openindiana_ensure_libs text/gnu-patch runtime/gcc developer/library/lint system/header system/library/math/header-math file/gnu-coreutils
      ;;
  esac
}
