#!/usr/bin/env bash

requirements_opensuse_lib_installed()
{
  rpm -q --whatprovides "$1" >/dev/null || return $?
}

requirements_opensuse_ensure_libs()
{
  typeset lib
  typeset -a libs
  libs=()

  for lib
  do
    __rvm_package_installed_wrapper "$lib" \
      requirements_opensuse_lib_installed "$lib" ||
    libs+=( "$lib" )
  done

  (( ${#libs[@]} )) || return 0
  __rvm_try_sudo zypper install -y "${libs[@]}"
}

requirements_opensuse()
{
  case "$1" in
    (update-system)
      __rvm_try_sudo zypper refresh | __rvm_dotted "Updating repositories"
      ;;
    (rvm)
      requirements_opensuse_ensure_libs bash curl git patch
      ;;
    (jruby*)
      requirements_opensuse_ensure_libs java
      ;;
    (ir*)
      requirements_opensuse_ensure_libs mono
      ;;
    (opal)
      requirements_opensuse_ensure_libs nodejs
      ;;
    (*)
      requirements_opensuse_ensure_libs patterns-openSUSE-devel_basis gcc-c++ bzip2 readline-devel zlib-devel libxml2-devel libxslt-devel libyaml-devel libopenssl-devel libffi-devel libtool bison
      ;;
  esac
}
