#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/osx_brew"
source "$rvm_scripts_path/functions/requirements/osx_fink"
source "$rvm_scripts_path/functions/requirements/osx_port"
source "$rvm_scripts_path/functions/requirements/smf"

requirements_osx_before()
{
  typeset __type
  for __type in osx_brew osx_port osx_fink smf
  do
    if
      requirements_find_${__type}
    then
      __lib_type=${__type}
      return 0
    fi
  done

  # fallback
  __lib_type=osx_brew
}

requiremnts_osx_java_fail()
{
  which java >/dev/null 2>&1 || return $?
  java_version=$(java -version 2>&1  | awk -F'"' '/ version /{print $2}')
  case "$java_version" in
    (1.5.*)
      printf "%b" "\n\nWARNING: A very outdated JAVA version is being used ($java_version), it is strongly recommended that you upgrade to the latest version.\n\n"
      ;;
    (1.3.*|1.4.*)
      printf "%b" "\n\nERROR: Unsupported JAVA version $java_version. In order to install and use JRuby you must upgrade to the latest JAVA version.\n\n"
      return 1
      ;;
  esac
  true # for OSX
}
