#!/usr/bin/env bash

requirements_find_osx_port()
{
  if # find macports in PATH
    __rvm_which port >/dev/null 2>&1
  then
    return 0
  else # find macports out of PATH and link to rvm/bin
    typeset __binary
    for __binary in ~/opt/local/bin/port ~/.opt/local/bin/port /usr/local/bin/port /opt/local/bin/port
    do
      if
        [[ -f "${__binary}" && -s "${__binary}" && -x "${__binary}" ]]
      then
        # link to rvm_bin for easy adding to PATH
        ln -nfs "${__binary}" "${rvm_bin_path:-$rvm_path/bin}/port"
        return 0
      fi
    done
    return 1
  fi
}

requirements_osx_port_version_list()
{
  if __rvm_which $1 >/dev/null
  then $1 --version 2>/dev/null | sed -n -e '1{s/^.* //; p;}'
  fi
  port -q installed $1* 2>/dev/null | sed -e 's/.* @//' -e 's/_.*//' -e 's/ .*//'
}

requirements_osx_port_lib_installed()
{
  port -q installed $1 | GREP_OPTIONS="" \grep active >/dev/null || return $? ;
}

requirements_osx_port_libs_install()
{
  __rvm_try_sudo port install "$@" ||
  {
    typeset ret=$?
    # TODO: offer more help!
    rvm_warn "There were package installation errors, make sure to read the log."
    return $ret
  }
}

requirements_osx_port_before()
{
  requirements_osx_port_ensure_port_available || return $?

  typeset -ax port_libs
}

requirements_osx_port_libs_default()
{
  port_libs=(
    autoconf automake libtool pkgconfig
  )
  case "$1" in
    (*-head) __rvm_which git >/dev/null || port_libs+=( git )
      ;;
  esac
  # install gcc-4.2 only if not yet available
  if
    __rvm_compiler_is_llvm
  then
    port_libs+=( apple-gcc42 )
  fi
  port_libs+=(
    libiconv libyaml libffi readline libksba openssl curl-ca-bundle sqlite3 zlib gdbm
  )
  if   requirements_osx_port_lib_installed ncurses
  then port_libs+=( ncurses  )
  elif requirements_osx_port_lib_installed ncursesw
  then port_libs+=( ncursesw )
  else port_libs+=( ncurses  )
  fi
  requirements_check "${port_libs[@]}" || return $?
}

requirements_osx_port_update_system()
{
  __rvm_try_sudo port -dv selfupdate || return $?
}

requirements_osx_port_define()
{
  case "$1" in
    (rvm)
      true
      ;;
    (jruby*head)
      __rvm_which git >/dev/null || requirements_check git
      requiremnts_osx_java_fail  || return $?
      ;;
    (jruby*)
      requiremnts_osx_java_fail || return $?
      ;;
    (ir*)
      __rvm_which mono >/dev/null 2>&1 || return $?
      ;;
    (opal)
      requirements_osx_port_libs_ensure node
      ;;
    (ruby*head)
      __rvm_which git >/dev/null || requirements_check git
      requirements_osx_port_libs_default "$1"
      requirements_version_minimal autoconf 2.67
      ;;
    (*-head)
      __rvm_which git >/dev/null || requirements_check git
      requirements_osx_port_libs_default "$1"
      ;;
    (*)
      requirements_osx_port_libs_default "$1"
      ;;
  esac
}

requirements_osx_port_after()
{
  typeset port_root
  port_root="$(dirname $(dirname $(__rvm_which port 2>/dev/null)))"
  test "x${port_root}" = "x" && port_root="/opt/local"
  __rvm_update_configure_opt_dir "$1" "${port_root}" || return $?
  unset port_libs

  __rvm_add_to_path prepend "${port_root}/bin"
  rvm_debug "PATH=$PATH"

  rvm_requiremnts_fail_or_run_action 2 \
    "Skipping certificates update, make sure your certificates are up to date." \
    requirements_osx_update_openssl_cert "${port_root}/bin/openssl" || return $?
}


requirements_osx_port_install_port()
{
  typeset macports_version
  macports_version="$(
    __rvm_curl https://distfiles.macports.org/MacPorts/ |
    grep -Eo "<a href=\"MacPorts-[[:digit:]\.]+.tar.bz2\">" |
    awk -F'"' '{print $2}' | sort | tail -n 1
  )" #'
  macports_version="${macports_version%.tar.bz2}"
  : macports_version:${macports_version:=MacPorts-2.1.3}
  mkdir "${rvm_src_path}/${macports_version}"
  cd    "${rvm_src_path}/${macports_version}"
  __rvm_curl "https://distfiles.macports.org/MacPorts/${macports_version}.tar.bz2" | tar -xj --strip 1
  __rvm_check_pipestatus ${PIPESTATUS[@]} ${pipestatus[@]} || return $?
  ./configure &&
  make &&
  __rvm_try_sudo make install || return $?
  __rvm_which port >/dev/null || ln -s /opt/local/bin/port "${rvm_bin_path}"/port
}

requirements_osx_port_ensure_port_available()
{
  __rvm_which port >/dev/null ||
  {
    __rvm_which make > /dev/null &&
    {
      __rvm_which clang > /dev/null ||
      __rvm_which gcc-4.2 > /dev/null
    } ||
    {
      rvm_error "Can not find compiler and 'make' tool - make sure Xcode and/or Command Line Tools are installed."
      return 11
    }
    rvm_requiremnts_fail_or_run_action 2 \
      "Requested installation with macports libs, but macports is not available." \
      __rvm_log_command port_install "Installing macports" requirements_osx_port_install_port ||
      return $?
  }
}
