#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/centos"

requirements_redhat_define_glibc()
{
  requirements_check glibc-headers glibc-devel
}

requirements_redhat_define_libyaml()
{
  case "$1" in
    (ruby-1*) requirements_check libyaml-devel ;;
  esac
}

requirements_redhat_define_openssl()
{
  requirements_check openssl-devel
}

requirements_redhat_define()
{
  __lib_type=centos
  
  requirements_centos_define "$@"
}
