#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/gentoo"

requirements_sabayon_define()
{
  requirements_gentoo_define "$@"
}

requirements_sabayon_lib_installed()
{
  __rvm_try_sudo equo query installed "$1" >/dev/null || return $?
}

requirements_sabayon_libs_install()
{
  __rvm_try_sudo equo install "$@" || return $?
}

requirements_sabayon_update_system()
{
  __rvm_try_sudo equo update || return $?
}
