#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/centos"

requirements_scientific_define_glibc()
{
  requirements_check glibc-headers glibc-devel
}

requirements_scientific_define_libyaml()
{
  requirements_check libyaml-devel
}

requirements_scientific_define_openssl()
{
  requirements_check openssl-devel
}

requirements_scientific_define()
{
  __lib_type=centos

  requirements_centos_define "$@"
}
