#!/usr/bin/env bash

set -e

function requirements_gentoo()
{
  typeset -a command_to_run command_flags
  command_to_run=()
  command_flags=()

  while
    (( $# ))
  do
    case "$1" in
      (echo)
        command_to_run+=( $1 )
        shift
        ;;
      (force|run)
        shift
        ;;
      (*)
        break
        ;;
    esac
  done

  (( UID == 0 )) || command_to_run+=( sudo )

  while
    (( $# ))
  do
    case "$1" in
      (update-system)
        true
        ;;
      (rvm)
        "${command_to_run[@]}" pkgin bash curl git patch
        ;;
      (jruby-head*)
        "${command_to_run[@]}" pkgin jdk apache-ant
        ;;
      (jruby*)
        "${command_to_run[@]}" pkgin jdk
        ;;
      (ir*)
        "${command_to_run[@]}" pkgin mono
        ;;
      (opal)
        "${command_to_run[@]}" pkgin node-devel
        ;;
      (*)
        "${command_to_run[@]}" pkgin coreutils gcc47 gmake readline scmgit-base sqlite3 libxml2 libxslt ncurses autoconf automake
        ;;
    esac
    shift
  done
}

requirements_gentoo "$@"
