#!/usr/bin/env bash

requirements_solaris_lib_installed()
{
        pkg info "$1" >/dev/null  2>&1 || return $?
}

requirements_solaris_lib_install()
{
        __rvm_try_sudo pkg install "$@" || return $?
}

requirements_solaris_ensure_libs()
{
        typeset -a packages_installed packages_missing packages_to_install
        __rvm_filter_installed_packages solaris "$@" || return $?
}

requirements_solaris_update_system()
{
  __rvm_try_sudo pkg refresh && __rvm_try_sudo pkg update
}

requirements_solaris_run()
{
  case "$1" in
    (update-system)
      rvm_requiremnts_fail_or_run_action 3 \
        "Skipping \`pkg update\` make sure your system is up to date." \
        requirements_solaris_update_system || return $?
      
      ;;
    (rvm)
      requirements_solaris_ensure_libs bash curl git text/gnu-patch
      ;;
    (jruby-head*)
      requirements_solaris_ensure_libs jdk apache-ant
      ;;
    (jruby*)
      requirements_solaris_ensure_libs jdk
      ;;
    (ir*)
      requirements_solaris_ensure_libs mono
      ;;
    (opal)
      requirements_solaris_ensure_libs node-devel
      ;;
    (*)
      requirements_solaris_ensure_libs text/gnu-patch developer/gcc-45 \
        system/header system/library/math file/gnu-coreutils
      ;;
  esac
}
