#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/opensuse"

requirements_suse_define_libyaml()
{
    requirements_opensuse_lib_installed libyaml-devel ||
    {
      requirements_check pkg-config
      requirements_rvm_pkg_lib_installed_custom yaml
    }
}

requirements_suse_define()
{
  __lib_type=opensuse
  requirements_opensuse_define "$@"
}

requirements_suse_after()
{
  requirements_rvm_pkg_configure "$1" yaml
}
