#!/usr/bin/env bash

requirements_synology_lib_installed()
{
  ipkg list_installed | __rvm_grep "^$1" >/dev/null 2>&1 || return $?
}

requirements_synology_lib_available()
{
  ipkg list | __rvm_grep "^$1" >/dev/null 2>&1 || return $?
}

requirements_synology_libs_install()
{
  __rvm_try_sudo ipkg add -z "$@" || return $?
}

requirements_synology_define()
{
  case "$1" in
    (rvm)
      requirements_check bash curl
      ;;
    (jruby*head)
      requirements_check jdk apache-ant git
      ;;
    (jruby*)
      requirements_check jdk
      ;;
    (ir*)
      requirements_check mono
      ;;
    (opal)
      requirements_check node
      ;;
    (*-head)
      requirements_check gcc autoconf automake libtool bison readline libyaml openssl git
      __rvm_update_configure_opt_dir "$1" "/usr/local"
      ;;
    (*)
      requirements_check gcc autoconf automake libtool bison readline libyaml openssl
      __rvm_update_configure_opt_dir "$1" "/usr/local"
      ;;
  esac
}
