#!/usr/bin/env bash

requirements_debian_lib_installed()
{
  dpkg-query -s "${1}:${__architecture}" >/dev/null 2>&1 ||
  dpkg-query -s "${1}:all"               >/dev/null 2>&1 ||
  dpkg-query -s "$1" 2>/dev/null | __rvm_grep "Architecture: ${__architecture}" >/dev/null ||
  dpkg-query -s "$1" 2>/dev/null | __rvm_grep "Architecture: all"               >/dev/null ||
  return $?
}

requirements_debian_libs_install()
{
  pkg install "$@" || return $?
}

requirements_debian_libs_remove()
{
  pkg --yes remove "$@" || return $?
}

requirements_debian_define_base()
{
  requirements_check "$@" \
    autoconf automake bison ca-certificates curl libc6-dev libffi-dev libgdbm-dev libncurses5-dev \
    libsqlite3-dev libtool libyaml-dev make openssl patch pkg-config sqlite3 zlib1g zlib1g-dev

  requirements_${_system_name_lowercase}_define_libgmp
  requirements_${_system_name_lowercase}_define_libreadline
}

requirements_debian_define()
{
  case "$1" in
    (rvm)
      requirements_check bash curl patch bzip2 ca-certificates gawk
      ;;

    (*)
      requirements_check clang coreutils curl gawk git gnupg gpgv \
                         libc++ libclang libclang-dev libllvm libxml2 make ncurses ncurses-ui-libs \
                         openssl openssl-dev openssl-tool readline sqlite tar zlib zlib-dev
      ;;
  esac
}
