#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_ubuntu_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_ubuntu_define_libreadline()
{
  if
    __rvm_version_compare ${_system_version} -ge 9
  then
    requirements_check libreadline-dev
  else
    requirements_check libreadline6-dev
  fi
}

requirements_trisquel_define_libssl()
{
  # Legacy libssl-dev required by older version of ruby has been renamed to libssl1.0-dev
  # starting from Trisquel 9 (based on Ubuntu 18.04 LTS "Bionic Beaver")

  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*)
      if
        __rvm_version_compare ${_system_version} -ge 9
      then
        undesired_check libssl-dev
        requirements_check libssl1.0-dev
      else
        requirements_check libssl-dev
      fi
      ;;

    (*)
      requirements_check libssl-dev
      ;;
  esac
}

requirements_trisquel_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
