#!/usr/bin/env bash

source "$rvm_scripts_path/functions/requirements/debian"

requirements_ubuntu_define_libgmp()
{
  requirements_check libgmp-dev
}

requirements_ubuntu_define_libreadline()
{
  if
    __rvm_version_compare ${_system_version} -ge 16.10
  then
    requirements_check libreadline-dev
  else
    requirements_check libreadline6-dev
  fi
}

requirements_ubuntu_define_libssl()
{
  # Legacy libssl-dev required by older version of ruby has been renamed to libssl1.0-dev
  # starting from Ubuntu 17.10 (Artful Aardvark)

  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*)
      if
        __rvm_version_compare ${_system_version} -ge 17.10
      then
        undesired_check libssl-dev
        requirements_check libssl1.0-dev
      else
        requirements_check libssl-dev
      fi
      ;;

    (*)
      requirements_check libssl-dev
      ;;
  esac
}

requirements_ubuntu_define_clang_llvm()
{
  if
    __rvm_version_compare ${_system_version} -ge 17.04
  then
    requirements_check clang-4.0 llvm-4.0 llvm-4.0-dev libc++-dev libc++abi-dev
    rvm_configure_flags+=( --cc=clang-4.0 --cxx=clang++-4.0 --llvm-config=llvm-config-4.0)
    __rvm_update_configure_env CXXFLAGS="-nostdinc++ -I/usr/include/c++/v1" LDFLAGS="-stdlib=libc++ -lc++"
  else
    requirements_check clang-3.6 llvm-3.6 llvm-3.6-dev
    rvm_configure_flags+=( --cc=clang-3.6 --cxx=clang++-3.6 --llvm-config=llvm-config-3.6)
  fi
}

requirements_ubuntu_define()
{
  __lib_type=debian
  requirements_debian_define "$@"
}
