#!/usr/bin/env bash

set -e

function requirements_unknown()
{
  typeset -a command_to_run
  command_to_run=( echo )

  while
    (( $# ))
  do
    case "$1" in
      (echo|run)
        shift
        ;;
      (force)
        shift
        ;;
      (*)
        break
        ;;
    esac
  done

  while
    (( $# ))
  do
    case "$1" in
      (update-system)
        "${command_to_run[@]}" "Always update your system first!"
        ;;
      (rvm)
        "${command_to_run[@]}" "Install: bash curl git patch"
        ;;
      (jruby*)
        "${command_to_run[@]}" "Install: openjdk ant"
        ;;
      (ir*)
        "${command_to_run[@]}" "Install: mono"
        ;;
      (opal)
        "${command_to_run[@]}" "Install: nodejs npm"
        ;;
      (*)
        "${command_to_run[@]}" "Install: build-essential openssl libreadline git zlib1g libyaml libsqlite3 sqlite3 libxml2 libxslt autoconf libc6 libgdbm ncurses automake libtool bison pkg-config"
        ;;
    esac
    shift
  done
}

requirements_unknown "$@"
