#!/usr/bin/env bash

requirements_unknown_install()
{
  echo "Install: $*"
}

requirements_unknown_binaries()
{
  typeset -a list
  list=()
  while
    (( $# ))
  do
    __rvm_which "$1" || list+=( "$1" )
    shift
  done
  (( ${#list[@]} )) || return 0
  requirements_unknown_install ${list[@]}
}

requirements_unknown_wait_key()
{
  rvm_log "press any key to continue"
  typeset _read_char_flag anykey
  [[ -n "${ZSH_VERSION:-}" ]] && _read_char_flag=k || _read_char_flag=n
  builtin read -${_read_char_flag} 1 -s -r anykey
}

requirements_unknown()
{
  case "$1" in
    (update-system)
      echo "Always update your system first!"
      ;;
    (rvm)
      requirements_unknown_binaries bash curl git patch
      ;;
    (jruby*)
      requirements_unknown_install openjdk ant
      ;;
    (ir*)
      requirements_unknown_install mono
      ;;
    (opal)
      requirements_unknown_install nodejs npm
      ;;
    (*)
      requirements_unknown_install build-essential openssl libreadline zlib1g libyaml libsqlite3 sqlite3 libxml2 libxslt autoconf libc6 libgdbm ncurses automake libtool bison pkg-config
      ;;
  esac
  requirements_unknown_wait_key
}
