#!/usr/bin/env bash

requirements_void_lib_installed()
{
  xbps-query -l | __rvm_grep "^$1" >/dev/null || return $?
}

requirements_void_libs_install()
{
  __rvm_try_sudo xbps-install -S "$@" || return $?
}

requirements_void_libs_remove()
{
  __rvm_try_sudo xbps-remove -R "$@" || return $?
}

requirements_void_define_base()
{
  requirements_check "$@" \
    autoconf automake bison ca-certificates curl libc6-dev libffi-dev libgdbm-dev libncurses5-dev \
    libreadline-dev libgmp-dev libssl-dev \
    libsqlite3-dev libtool libyaml-dev make openssl patch pkg-config sqlite3 zlib1g zlib1g-dev
}

requirements_void_define()
{
  if [[ "$1" == *head ]]
  then
      requirements_check git git-core
  fi

  case "$1" in
    (rvm)
      requirements_check bash curl patch bzip2 gawk
      ;;

    (jruby*)
      # Not implemented
      true
      ;;

    (ir*)
      # Not implemented
      true
      ;;

    (opal)
      # Not implemented
      true
      ;;

    (rbx*|rubinius*)
      # Not implemented
      true
      ;;

    (truffleruby*)
      # Not implemented
      true
      ;;

    (*)
      requirements_void_define_base g++ gcc
      ;;
  esac
}
