#!/bin/zsh

source ./test/setup
initialize_rvm


btu_run 'output=$(rvm gemdir)'
assert string_eq "$(gem env gemdir)" "$output"

btu_run 'output=$(rvm gemdir system)'
assert match "/Library/Ruby/Gems/1.8" "$output"

btu_run 'output=$(rvm gemdir system user)'
assert match ".gem/ruby/1.8" "$output"

btu_run 'output=$(rvm gemdir user)'
assert match ".gem/ruby/1.8" "$output"

btu_run 'output=$(rvm jruby gemdir)'
assert match ".rvm/gems/jruby/1.4.0" "$output"

btu_run 'output=$(rvm ree gemdir)'
assert match ".rvm/gems/ree/1.8.7" "$output"

btu_run 'output=$(rvm 1.9.1 gemdir)'
assert match ".rvm/gems/ruby/1.9.1" "$output"

if [[ -z "$rvm_teset_suite_flag" ]] ; then btu_summary ; fi

