#!/bin/zsh

source ./test/setup
initialize_rvm

# tests: 29
# assertions: 290

original_dir=$(pwd)
testset_dir="$(gem env gemdir)-testset"

setup_testset() {
  rvm 1.9.1 -m testset
  echo "Installing Rake"
  gem install rake --no-rdoc --no-ri
}

clear_testset() {
  if [ ! -z "$testset_dir" -a "$testset_dir" != '/' ] ; then rm -rf  $testset_dir ; fi
}

btu_test "rvm gemset testset"
assert string_eq "testset" $(gem env gemdir | xargs basename | sed "s/^$rvm_ruby_version-//")
clear_testset

btu_test 'gemset=\`rvm gemset name\`'
assert string_eq "testset" $gemset
clear_testset

btu_test 'gemset_dir=\`rvm gemset dir\`'
assert match "-test$" $gemset_dir
clear_testset

btu_test "rvm gemset dump"
assert match "-test$" $gemset_dir
clear_testset

btu_test "rvm gemset dump my_testset"
clear_testset

btu_test "rvm gemset dump my_testset.gemset"
clear_testset

btu_test "rvm gemset load"
# Should load testset.gemspec
clear_testset

btu_test "rvm gemset load my_testset.gemspec"
clear_testset

btu_test "rvm gemset delete test-gemset"
clear_testset

