#!/bin/zsh

source ./test/setup
initialize_rvm

# tests: 29
# assertions: 290

original_dir=$(pwd)

setup_testset() {
  rvm 1.9.1 -m testset
}

clear_gemset() {
  gemset=${1:-testset}
  testset_dir="$(gem env gemdir)-$gemset"
  if [ ! -z "$testset_dir" -a "$testset_dir" != '/' ] ; then rm -rf  $testset_dir ; fi
  rm -f testset.gems
}

setup_testset
btu_test "rvm gemset testset"
assert string_eq "testset" $(gem env gemdir | xargs basename | awk -F '-' '{$1=NULL;print}')
clear_gemset

btu_test 'gemset=`rvm gemset name`'
assert string_eq "testset" $gemset
clear_gemset

btu_test 'gemset_dir=\`rvm gemset dir\`'
assert match "1.9.1-testset$" $(gem env gemdir)
clear_gemset

gem build rvm.gemspec > /dev/null
gem install --no-rdoc --no-ri ./rvm*.gem > /dev/null
btu_test "rvm gemset dump"
assert file_exists 'testset.gems'
assert file_contains "^rvm" "testset.gems"
clear_gemset

gem build rvm.gemspec > /dev/null
gem install --no-rdoc --no-ri ./rvm*.gem > /dev/null
btu_test "rvm gemset dump my_testset"
assert file_exists 'my_testset.gems'
assert file_contains "^rvm" "my_testset.gems"
#clear_gemset

#btu_test "rvm gemset dump my_testset.gems"
#clear_gemset
#
#btu_test "rvm gemset load"
## Should load testset.gemspec
#clear_gemset
#
#btu_test "rvm gemset load my_testset.gemspec"
#clear_gemset
#
#btu_test "rvm gemset delete test-gemset"
#clear_gemset

