#!/bin/zsh

source ./test/setup
initialize_rvm

# tests: 29
# assertions: 290

original_dir=$(pwd)

setup_testset() {
  rvm 1.9.1
}

clear_gems() {
  gems=${1:-testset}
  testset_dir="$(gem env gemdir)-$gems"
  if [ ! -z "$testset_dir" -a "$testset_dir" != '/' ] ; then rm -rf  $testset_dir ; fi
  rm -f testset.gems
}

setup_testset
btu_test "rvm gems testset ; gemdir=\$(gem env gemdir)"
assert match "ruby\/1.9.1-testset$" "$gemdir"
clear_gems

btu_test 'rvm gems testset ; gems=\$(rvm gems name)'
assert string_eq "testset" "$gems"
clear_gems

btu_test 'rvm gems testset; gems_dir=\$(rvm gems dir)'
assert match "1.9.1-testset$" "$gems_dir"
clear_gems

gem build rvm.gemspec > /dev/null
gem install --no-rdoc --no-ri ./rvm*.gem > /dev/null
btu_test "rvm gems testset ; rvm gems dump"
assert file_exists 'testset.gems'
assert file_contains "^rvm" "testset.gems"
clear_gems

gem build rvm.gemspec > /dev/null
gem install --no-rdoc --no-ri ./rvm*.gem > /dev/null
btu_test "rvm gems testset ; rvm gems dump my_testset"
assert file_exists 'my_testset.gems'
assert file_contains "^rvm" "my_testset.gems"
clear_gems

btu_test "rvm gems dump my_testset.gems"
clear_gems

btu_test "rvm gems load"
# Should load testset.gemspec
clear_gems

btu_test "rvm gems load my_testset.gemspec"
clear_gems

btu_test "rvm gems delete test-gems"
clear_gems

if [ `basename $0` != "test_suite" ] ; then btu_summary ; fi

