#!/bin/zsh

source ./test/setup

initialize_rvm

btu_test "prompt=\$(rvm 1.9.1 ; scripts/rvm-prompt)"
assert string_eq "[ruby-1.9.1-p243]" "$prompt"

btu_test "prompt=\$(rvm 1.9.1-head ; scripts/rvm-prompt)"
assert string_eq "[ruby-1.9.1-head]" "$prompt"

btu_test "prompt=\$(rvm 1.8.6 ; scripts/rvm-prompt)"
assert string_eq "[ruby-1.8.6-p383]" "$prompt"

btu_test "prompt=\$(rvm ree ; scripts/rvm-prompt)"
assert string_eq "[ree-1.8.7-20090928]" "$prompt"

btu_test "prompt=\$(rvm ree ; ./scripts/rvm-prompt i)"
assert "string_eq" "[ree]" "$prompt"

btu_test "prompt=\$(rvm ree ; ./scripts/rvm-prompt i v)"
assert "string_eq" "[ree-1.8.7]" "$prompt"

btu_test "prompt=\$(rvm ree ; ./scripts/rvm-prompt v)"
assert "string_eq" "[1.8.7]" "$prompt"

btu_test "prompt=\$(rvm ree ; ./scripts/rvm-prompt v p)"
assert "string_eq" "[1.8.7-20090928]" "$prompt"

btu_test "prompt=\$(rvm ree-head ; scripts/rvm-prompt)"
assert string_eq "[ree-1.8.7-head]" "$prompt"

btu_test "prompt=\$(rvm 1.9.1 ; scripts/rvm-prompt p v i)"
assert string_eq "[p243-1.9.1-ruby]" "$prompt"

if [[ -z "$rvm_teset_suite_flag" ]] ; then btu_summary ; fi

