#!/usr/bin/env bash

source ./test/setup

initialize_rvm

btu_run "prompt=\$(rvm 1.9.1 ; binscripts/rvm-prompt)"
assert string_eq "ruby-1.9.1-p378" "$prompt"

btu_run "prompt=\$(rvm 1.9.1-head ; binscripts/rvm-prompt)"
assert string_eq "ruby-1.9.1-head" "$prompt"

btu_run "prompt=\$(rvm 1.8.6 ; binscripts/rvm-prompt)"
assert string_eq "ruby-1.8.6-p399" "$prompt"

btu_run "prompt=\$(rvm ree ; binscripts/rvm-prompt)"
assert string_eq "ree-1.8.7-2009.10" "$prompt"

btu_run "prompt=\$(rvm ree ; binscripts/rvm-prompt i)"
assert string_eq "ree" "$prompt"

btu_run "prompt=\$(rvm ree ; binscripts/rvm-prompt i v)"
assert string_eq "ree-1.8.7" "$prompt"

btu_run "prompt=\$(rvm ree ; binscripts/rvm-prompt v)"
assert string_eq "1.8.7" "$prompt"

btu_run "prompt=\$(rvm ree ; binscripts/rvm-prompt v p)"
assert string_eq "1.8.7-2009.10" "$prompt"

btu_run "prompt=\$(rvm ree-head ; binscripts/rvm-prompt)"
assert string_eq "ree-1.8.7-head" "$prompt"

btu_run "prompt=\$(rvm 1.9.1 ; binscripts/rvm-prompt p v i)"
assert string_eq "p378-1.9.1-ruby" "$prompt"

btu_run "prompt=\$(rvm system ; binscripts/rvm-prompt)"
assert string_eq "system" "$prompt"

if [[ -z "$rvm_teset_suite_flag" ]] ; then btu_summary ; fi

