#!/bin/zsh

source ./test/setup
initialize_rvm

# tests: 29
# assertions: 290

validate_select() {
  assert match $valid_string $rvm_ruby_home
  assert match $(__btu_db "test/rubies/$valid_string" "gem_home") $rvm_ruby_gem_home
  assert match $valid_string $rvm_ruby_home
  assert match "$(echo $valid_string | awk -F'-' '{print $1"/"$2}')" $rvm_ruby_gem_home
  assert match $valid_string $rvm_ruby_string
  assert match $valid_string $rvm_ruby_log_path
  assert match $valid_string $rvm_ruby_package_name
  assert match "src/$valid_string" $rvm_ruby_src_path
  assert match "$valid_string/bin/ruby" $rvm_ruby_binary
  assert match "$valid_string/.irbrc" $rvm_ruby_irbrc
}

for valid_string in $(echo $rubies) ; do
  btu_test "rvm_ruby_string='$valid_string' ; __rvm_select"
  validate_select
done

command="rvm_ruby_string=\$rvm_ruby_string ; __rvm_select"
rvm_ruby_string='1.8.5'      ; valid_string="ruby-1.8.5-p231"    ; btu_test $command ; validate_select
rvm_ruby_string='ruby-1.8.5' ; valid_string="ruby-1.8.5-p231"    ; btu_test $command ; validate_select
rvm_ruby_string='1.8.6'      ; valid_string="ruby-1.8.6-p383"    ; btu_test $command ; validate_select
rvm_ruby_string='ruby-1.8.6' ; valid_string="ruby-1.8.6-p383"    ; btu_test $command ; validate_select
rvm_ruby_string='1.8.7'      ; valid_string="ruby-1.8.7-p174"    ; btu_test $command ; validate_select
rvm_ruby_string='ruby-1.8.7' ; valid_string="ruby-1.8.7-p174"    ; btu_test $command ; validate_select
rvm_ruby_string='1.9.1'      ; valid_string="ruby-1.9.1-p243"    ; btu_test $command ; validate_select
rvm_ruby_string='ruby-1.9.1' ; valid_string="ruby-1.9.1-p243"    ; btu_test $command ; validate_select
rvm_ruby_string='ree-1.8.6'  ; valid_string="ree-1.8.6-20090610" ; btu_test $command ; validate_select
rvm_ruby_string='ree'        ; valid_string="ree-1.8.7-20090928" ; btu_test $command ; validate_select
rvm_ruby_string='ree-1.8.7'  ; valid_string="ree-1.8.7-20090928" ; btu_test $command ; validate_select
rvm_ruby_string='ree-head'   ; valid_string='ree-1.8.7-head'     ; btu_test $command ; validate_select
rvm_ruby_string='jruby-1.4.0'; valid_string="jruby-1.4.0RC1"     ; btu_test $command ; validate_select
rvm_ruby_string='jruby-1.3.1'; valid_string="jruby-1.3.1"        ; btu_test $command ; validate_select
rvm_ruby_string='jruby'      ; valid_string="jruby-1.3.1"        ; btu_test $command ; validate_select

if [ `basename $0` = "selector_test" ] ; then btu_summary ; fi

