#!/usr/bin/env bash

source ./test/setup
initialize_rvm

unset result ; btu_run ${rvm_scripts_path}'/match "a" "a" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark" "a" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark" "^s" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark" "k$" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark" "s$" ; result=$?'
assert number_eq 1 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark" "^k" ; result=$?'
assert number_eq 1 $result

unset result ; btu_run ${rvm_scripts_path}'/match "1.9.1" "^[0-9]\.[0-9]" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark.rb" "\.rb$" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark.gems" "\.gems$" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "snark.gem" "\.gem$" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "1.9.1${rvm_gemset_separator}snark" "^.+${rvm_gemset_separator}.+$" ; result=$?'
assert number_eq 0 $result

unset result ; btu_run ${rvm_scripts_path}'/match "1.9.1" "^.+${rvm_gemset_separator}.+$" ; result=$?'
assert number_eq 1 $result

if [[ -z "$rvm_teset_suite_flag" ]] ; then btu_summary ; fi

