#!/usr/bin/env bash

source ./test/setup
initialize_rvm

heat './scripts/match "a" "a"'
assert number_eq 0 $result

heat './scripts/match "snark" "a"'
assert number_eq 0 $result

heat './scripts/match "snark" "^s"'
assert number_eq 0 $result

heat './scripts/match "snark" "k$"'
assert number_eq 0 $result

heat './scripts/match "snark" "s$"'
assert number_eq 1 $result

heat './scripts/match "snark" "^k"'
assert number_eq 1 $result

heat './scripts/match "1.9.1" "^[0-9]\.[0-9]"'
assert number_eq 0 $result

heat './scripts/match "snark.rb" "\.rb$"'
assert number_eq 0 $result

heat './scripts/match "snark.gems" "\.gems$"'
assert number_eq 0 $result

heat './scripts/match "snark.gem" "\.gem$"'
assert number_eq 0 $result

heat './scripts/match "1.9.1${rvm_gemset_separator}snark" "^.+${rvm_gemset_separator}.+$"'
assert number_eq 0 $result

heat './scripts/match "1.9.1" "^.+${rvm_gemset_separator}.+$"'
assert number_eq 1 $result

if [[ -z "$rvm_teset_suite_flag" ]] ; then btu_summary ; fi

