#!/usr/bin/env bash

after_cd_hooks=($(
  find -L "${rvm_path:-"$HOME/.rvm"}/hooks" -iname 'after_cd_*' -type f
))

for after_cd_hook in "${after_cd_hooks[@]}"
do
  if [[ -x "${after_cd_hook}" ]]
  then
    . "${after_cd_hook}"
  fi
done
