#!/usr/bin/env bash

. "${rvm_path}/scripts/functions/hooks/jruby"

if [[ "${rvm_ruby_string}" =~ "jruby" ]]
then
  jruby_options_append "${PROJECT_JRUBY_OPTS[@]}"
else
  jruby_options_remove "${PROJECT_JRUBY_OPTS[@]}"
  jruby_clean_project_options
fi
