#!/usr/bin/env bash

if [[ "$rvm_ruby_string" =~ "jruby" ]]
then
  ngserver_running()
  {
    ps aux | \grep -v grep | \grep -q -- '-Dsun.java.command=com.martiansoftware.nailgun.NGServer'
  }
  jruby()
  {
    if ngserver_running
    then
      command jruby --ng "$@"
    else
      command jruby "$@"
    fi
  }
  ruby()
  {
    jruby "$@"
  }
  if ! ngserver_running
  then
    JRUBY_OPTS='' jruby --ng-server 2>&1 1>/dev/null &
  fi
else
  unset -f ngserver
  unset -f jruby
  unset -f ruby
  export ruby jruby ngserver
fi
