#!/usr/bin/env bash

if [[ "${rvm_ruby_string}" =~ "jruby" ]]
then
  . "${rvm_path}/scripts/functions/hooks/jruby"

  if ! jruby_ngserver_is_running
  then
    (JRUBY_OPTS='' jruby --ng-server 2>&1 1>/dev/null)&
  fi
else
  unset -f ngserver
  unset -f jruby
  unset -f ruby

  export ruby jruby ngserver
fi
