#!/usr/bin/env bash

topaz_install()
{
    __rvm_cd "${rvm_src_path}"
    __rvm_fetch_ruby || return $?

    chmod +x "${rvm_ruby_home}/bin/topaz"

    rvm_create_flag=1 __rvm_use

    __rvm_bin_script
}
