#!/usr/bin/env bash

# Base is a collection general files + commonely included
# setup functions.

# Load the general scripts.
# Use rvm_base_except="" to override the except.
for script_name in initialize utility selector ; do
  if echo "${rvm_base_except:-""}" | \grep -vq "$script_name" ; then
    source "$rvm_path/scripts/$script_name"
  fi
done ; unset script_name rvm_base_except

  #for option in errexit noclobber nounset ; do
  #  set -o $option
  #done

  #if [[ -z "${ZSH_VERSION:-""}" ]] ; then
  #  set -o errtrace
  #  set -o pipefail
  #fi

if [[ ${rvm_trace_flag:-0} -gt 0 ]]; then
  export rvm_trace_flag=1
  set -o xtrace
fi

if [[ -n "${ZSH_VERSION:-""}" ]] ; then
  __array_start=1
else
  __array_start=0
fi

export BUNDLE_PATH GEM_HOME GEM_PATH $(env | awk -F= -v ORS=' ' '/rvm_/{print $1}')

# Cleanup tmp on exit.
trap "__rvm_cleanup_temp_for '$$'" 0 1 2 3 15
