#!/usr/bin/env bash

# Base is a collection general files + commonely included
# setup functions.

# Load the general scripts.
# Use rvm_base_except="" to override the except.
for script_name in initialize utility selector ; do
  if echo "${rvm_base_except:-""}" | \grep -vq "$script_name" ; then
    source "$rvm_scripts_path"/$script_name
  fi
done ; unset script_name rvm_base_except

  for option in errexit noclobber nounset ; do
    set -o $option
  done

  if [[ -z "${ZSH_VERSION:-""}" ]] ; then
    set -o errtrace
    set -o pipefail
  fi

if [[ ${rvm_trace_flag:-0} -gt 0 ]]; then
  export rvm_trace_flag=1
  set -o xtrace
fi

# Cleanup tmp on exit.
trap "__rvm_cleanup_temp_for '$$'" 0 1 2 3 15
