#!/usr/bin/env bash

# Source a .rvmrc file in a directory after changing to it, if it exists.
cd() {
  builtin cd "$@"
  if [[ "$rvm_project_rvmrc" != 0 ]] ; then
    local cwd ; cwd=$(pwd)
    while : ; do
      if [[ -f "$cwd/.rvmrc" ]] ; then source "$cwd/.rvmrc" ; break ; fi
      cwd=$(dirname $cwd)
      if [[ -z "$cwd" ]] || [[ "$HOME" = "$cwd" ]] || [[ "/" = "$cwd" ]] ; then
        if [[ "$rvm_project_rvmrc_default" != 0 ]] ; then
          rvm default 1>/dev/null 2>&1
        fi
        break
      fi
    done
  fi
}

