#!/usr/bin/env bash

# Source a .rvmrc file in a directory after changing to it, if it exists.
# To disable this fature, set rvm_project_rvmrc=0 in $HOME/.rvmrc
if [[ "$rvm_project_rvmrc" -ne 0 ]] ; then
  if [[ -n "$ZSH_VERSION" ]]; then
    # On zsh, use chpwd_functions
    chpwd_functions=( "${chpwd_functions[@]}" __rvm_project_rvmrc )
  else
    cd() {
      builtin cd "$@"
      __rvm_project_rvmrc
    }
  fi
fi
