#!/usr/bin/env bash

usage()
{
  printf "%b" "
ERROR:

    $1

Usage:

    db database_file {{key}} {{value}} # set
    db database_file {{key}}           # get
    db database_file {{key}} unset     # unset

" >&2
  exit 1
}

database_file="${1:-}"
if [[ -n "$database_file" ]]
then shift
else usage "Database file not given."
fi

key="${1:-}"
if [[ -n "$key" ]]
then shift
else usage "Key not given"
fi

value="$*"

if (( ${escape_flag:-0} ))
then escaped_key="$(\printf "%b" "$key" | \sed -e 's#\\#\\#g' -e 's#/#\\/#g' -e 's#\.#\.#g')"
else escaped_key="$key"
fi

[[ -f "$database_file" ]] ||
{
  directory=$(dirname "$database_file")
  [[ -d "$directory" ]] || mkdir -p "$directory"
  touch "$database_file"
}

db_remove()
{
  \sed -e "s#^$escaped_key=.*\$##"  -e '/^$/d' "$database_file" > "$database_file.new"
  \mv -f "$database_file.new" "$database_file"
}

case "$value" in
  (unset|delete)
    db_remove
    ;;
  ("") # get
    \awk -F= '/^'"$escaped_key"'=/' "$database_file" | \sed -e "s#^$escaped_key=##" -e '/^$/d'
    ;;
  (*) # set
    db_remove
    printf "%b=%b\n" "$escaped_key" "$value" >> "$database_file"
    ;;
esac
