#!/usr/bin/env bash

__rvm_if_sudo()
{
  typeset -a __command
  __command=()
  (( UID == 0 )) || __command+=( \sudo )
  __command+=( $@ )
  "${__command[@]}" || return $?
}

__rvm_fix_permissions_fix()
{
  __rvm_if_sudo chown -R "${__user}" "${rvm_path}"
  case "${__user}" in
    (*:*)
      __rvm_if_sudo chmod -R g+w "${rvm_path}"
      ;;
  esac
}

__rvm_fix_permissions_select()
{
  case "${__user}" in
    ("")
      if (( ${rvm_user_install_flag:=0} == 0 ))
      then __user="system"
      else __user="user"
      fi
      ;;
  esac
  case "${__user}" in
    (system)
      __user=":${rvm_group_name:-rvm}"
      ;;
    (user)
      __user="$USER"
      ;;
  esac
}

__rvm_fix_permissions()
{
  typeset __user="${1:-}"
  __rvm_fix_permissions_select
  __rvm_fix_permissions_fix
}

__rvm_fix_permissions "${args[@]}"
