#!/usr/bin/env bash

source $rvm_scripts_path/utility
source $rvm_scripts_path/selector

if [[ ! -z "$rvm_trace_flag" ]] ; then set -x ; export rvm_trace_flag ; fi
rvm_ruby_gem_home="${rvm_ruby_gem_home:-$GEM_HOME}"

if [[ ! -d "$rvm_ruby_gem_home" ]] && command -v gem > /dev/null 2>&1; then rvm_ruby_gem_home="$(gem env home)" ; fi

trap "if [[ -d $rvm_tmp_path/ ]] && [[ -s $rvm_tmp_path/$$ ]] ; then rm -f $rvm_tmp_path/$$ > /dev/null 2>&1 ; fi ; exit" 0 1 2 3 15

__rvm_gemset_name() {
   __rvm_gemset_gemdir |  awk -F${rvm_gemset_separator} '{print $2}'
}

__rvm_gemset_dir() {
  echo "$rvm_ruby_gem_home"
}

__rvm_gemset_create() {
  rvm_ruby_gem_prefix=$(echo $rvm_ruby_gem_home | sed 's/'${rvm_gemset_separator}'.*$//')
  for gemset in $(echo $gems_args) ; do
    gem_home="${rvm_ruby_gem_prefix}${rvm_gemset_separator}${gems_args/ /}"
    mkdir -p $gem_home
    ln -nfs "$HOME/.gem/cache" "$gem_home/cache"
    $rvm_scripts_path/log "info" "Gemset '$gemset' created."
  done ; unset gem_home
}

__rvm_gemset_list() {
  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi

  $rvm_scripts_path/log "info" "gemsets : for $rvm_ruby_string (found in $rvm_gems_path/)"

  if [[ ! -z "$rvm_gems_path" ]] ; then
    if [[ ! -z $rvm_ruby_string ]] ; then
      for gemdir in $rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator}* ; do
        echo "$gemdir" | awk -F${rvm_gemset_separator} '{print $2}'
      done
    else
      $rvm_scripts_path/log "error" "\$rvm_ruby_string is not set!"
    fi
  else
    $rvm_scripts_path/log "error" "\$rvm_gems_path is not set!"
  fi
}

__rvm_gemset_delete() {
  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
  if [[ ! -z "$rvm_gemset_name" ]] ; then
    gemdir="$rvm_gems_path/$rvm_ruby_string${rvm_gemset_separator}$rvm_gemset_name"
    if [[ -d "$gemdir" ]] && [[ "$gemdir" != '/' ]] && [[ ! -z "$rvm_force_flag" ]] ; then
        rm -rf  "$gemdir"
    elif [[ -d "$gemdir" ]] ; then
      $rvm_scripts_path/log "warn" "Are you SURE you wish to remove the entire gemset directory '$rvm_gemset_name' ($gemdir)?"
      echo -n "(anything other than 'yes' will cancel) > "
      read response
      if [[ "yes" = "$response" ]] ; then
        rm -f $gemdir/cache && rm -rf $gemdir
      else
        $rvm_scripts_path/log "info" "Not doing anything, phew... close call that one eh?"
      fi
    else
      $rvm_scripts_path/log "info" "$gemdir already does not exist."
    fi ; unset gemdir
  else
    $rvm_scripts_path/log "error" "A gemset name must be specified in order to delete a gems."
  fi
}

__rvm_gemset_empty() {
  if [[ -z "$rvm_ruby_gem_home" ]] ; then __rvm_select ; fi
  gemdir="$rvm_ruby_gem_home"
  if [[ -d "$gemdir" ]] && [[ "$gemdir" != '/' ]] && [[ ! -z "$rvm_force_flag" ]] ; then
    cd $gemdir && rm -rf ./bin/* ./doc/* ./gems/* ./specifications/*
  elif [[ -d "$gemdir" ]] ; then
    $rvm_scripts_path/log "warn" "Are you SURE you wish to remove the installed gemset for gemset '$(basename $gemdir)' ($gemdir)?"
    echo -n "(anything other than 'yes' will cancel) > "
    read response
    if [[ "yes" = "$response" ]] ; then
      cd $gemdir && rm -rf ./bin/* ./doc/* ./gems/* ./specifications/*
    else
      $rvm_scripts_path/log "info" "Not doing anything, phew... close call that one eh?"
    fi
  else
    $rvm_scripts_path/log "info" "$gemdir already does not exist."
  fi ; unset gemdir
}

# Migrate gemsets from ruby X to ruby Y
__rvm_gemset_copy() {
  source_ruby="$(echo $gems_args | awk '{print $1}')"
  destination_ruby="$(echo $gems_args | awk '{print $2}')"
  if [[ -z "$source_ruby" ]] ; then
    $rvm_scripts_path/log "error" "Source and destination must be specified: 'rvm gemset copy X Y'"
  fi
  if [[ -z "$destination_ruby" ]] ; then
    $rvm_scripts_path/log "error" "Source and destination must be specified: 'rvm gemset copy X Y'"
  fi
  source_path="$(rvm $source_ruby gem env gemdir | tail -n 1)"
  destination_path="$(rvm $destination_ruby gem env gemdir | tail -n 1)"
  if [[ -d "$source_path" ]] ; then
    if [[ ! -d "$destination_path" ]] ; then mkdir -p $destination_path ; fi
    $rvm_scripts_path/log "info" "Copying gemset from $source_ruby to $destination_ruby" ;
    for dir in bin doc gems specifications ; do
      mkdir -p "$destination_path/$dir"
      cp -Rf "$source_path/$dir" "$destination_path/"
    done
  else
    $rvm_scripts_path/log "error" "Gems directory does not exist for $source_path ($source_path)"
    return 1
  fi

  unset source_ruby destination_ruby source_path destination_path
}

__rvm_gemset_export() {
  rvm_file_name="${rvm_file_name:-$gems_args}"

  if [[ ! -z "$rvm_ruby_gem_home" ]] ; then
    export GEM_HOME="$rvm_ruby_gem_home"
    export GEM_PATH="$rvm_ruby_gem_home/bin:$rvm_gems_path/$rvm_ruby_string${rvm_gemset_separator}global/bin"
    export BUNDLE_PATH="$rvm_ruby_gem_home"
  fi

  if [[ -z "$rvm_file_name" ]] ; then
    if [[ ! -z "$rvm_gemset_name" ]] ; then
      rvm_file_name="$rvm_gemset_name.gems"
    else
      rvm_file_name="default.gems"
    fi
  fi

  $rvm_scripts_path/log "info" "Exporting current environments gemset to $rvm_file_name"

  touch $rvm_file_name
  echo "# $rvm_file_name generated gem export file. Note that any env variable settings will be missing. Append these after using a ';' field separator" > $rvm_file_name
  for gem in $(gem list | sed 's#[\(|\)]##g' | sed 's#, #,#g' | tr ' ' ';') ; do
    name="$(echo $gem | awk -F';' '{print $1}')"
    if [[ -z "$rvm_latest_flag" ]] ; then
      versions="$(echo $gem | awk -F';' '{print $2}' | sed 's#,# #g')"
      for version in $versions ; do
        echo "$name -v$version" >> $rvm_file_name
      done ; unset version versions
    else
      echo "$name" >> $rvm_file_name
    fi ; unset name
  done ; unset file_name
}

__rvm_gemset_import() {

  if [[ ! -z "$rvm_ruby_gem_home" ]] ; then
    export GEM_HOME="$rvm_ruby_gem_home"
    export GEM_PATH="$rvm_ruby_gem_home/bin:$rvm_gems_path/$rvm_ruby_string${rvm_gemset_separator}global/bin"
    export BUNDLE_PATH="$rvm_ruby_gem_home"
  fi

  if [[ ! -z "$(echo "$gems_args" | awk '/\.gem.*$/')" ]] ; then
    rvm_gemset_name="$(echo "$gems_args" | sed 's#\.gem.*##g' | sed 's# ##g')"
  else
    rvm_gemset_name="$(echo "$gems_args" | sed 's# ##g')"
  fi

  if [[ -s "$rvm_gemset_name.gems" ]] ; then
    rvm_file_name="$rvm_gemset_name.gems"
  elif [[ -s "default.gems" ]] ; then
    rvm_file_name="default.gems"
  elif [[ -s "system.gems" ]] ; then
    rvm_file_name="system.gems"
  elif [[ -s ".gems" ]] ; then
    rvm_file_name=".gems"
  else
    $rvm_scripts_path/log "error" "No *.gems file found."
    return 1
  fi

  mkdir -p "$rvm_gems_path/cache" # Ensure the base cache dir is initialized.

  if [[ -s "$rvm_file_name" ]] ; then
    echo "Importing  $rvm_file_name file..."
    rvm_ruby_gem_list=$(\ls $rvm_ruby_gem_home/specifications/ 2> /dev/null | sed 's#.gems.*$##' 2> /dev/null)

    while read -r line
    do # Keep this on 2nd line :(
      if [[ ! -z "$(echo $line | sed 's/\s//g')" ]] ; then
        gems_args="$line" ; __rvm_gem_install
      fi
    done < <(awk '/^[^#]+/{print}' "${rvm_file_name}")
  else
    $rvm_scripts_path/log "error" "${rvm_file_name} does not exist to import from."
  fi
}

__rvm_parse_gems_args() {
  gem="$(echo $gems_args | awk -F';' '{print $1}')"
  gem_prefix="$(echo $gems_args | awk -F';' '{print $2}')"
  if $rvm_scripts_path/match "$gem" "\.gem$" ; then
    gem_name="$(basename $gem | sed 's#\.gem##' | awk -F'-' '{$NF=NULL;print}')"
    gem_version="$(basename $gem | sed 's#\.gem##' | awk -F'-' '{print $NF}' )"
    gem_postfix="$(basename $gem | sed "s#.*\.gem##")"
  else
    gem_name="$(echo $gem | awk '{print $1}')"
    if $rvm_scripts_path/match "$gem" "--version" ; then
      gem_version="$(echo $gem | sed 's#.*--version[=]*[ ]*##' | awk '{print $1}')"
      gem_postfix="$(echo $gem | sed "s#${gem_name/ /}##" | sed "s#--version[=]*[ ]*${gem_version/ /}##")"
    elif $rvm_scripts_path/match "$gem" "-v" ; then
      gem_version="$(echo $gem | sed 's#.*-v[=]*[ ]*##' | awk '{print $1}')"
      gem_postfix="$(echo $gem | sed "s#${gem_name/ /}##" | sed "s#-v[=]*[ ]*${gem_version/ /}##")"
    else
      unset gem_version # no version
    fi
  fi

  if [[ -s "$gem" ]] ; then
    gem_file_name="$gem"
  elif $rvm_scripts_path/match "$gem" ".gem$" ; then
    gem_file_name="$gem"
  elif [[ -z "${gem_version/ /}" ]] ; then
    gem_file_name="${gem_name/ /}*.gem"
  else # version
    gem_file_name="${gem_name/ /}-${gem_version/ /}.gem"
  fi
}

# Install a gem
__rvm_gem_install() {
  # First we parse the gem args to pick apart the pieces.

  __rvm_parse_gems_args

  # Now we determine if a .gem cache file is already installed
  if [[ -z "$rvm_force_flag" ]] && [[ -f "${rvm_ruby_gem_home}/specifications/$(basename $gem_file_name)spec" ]] ; then
    unset gem
    $rvm_scripts_path/log "info" "$gem_name $gem_version exists, skipping (--force to re-install)"
  else
    if [[ -s "$gem" ]] ; then
      cache_file="$gem"
    elif [[ -s "$rvm_gems_path/cache/${gem_file_name}" ]] ; then
      cache_file="$rvm_gems_path/cache/${gem_file_name}"
    else
      cache_file="${cache_file:-$(\ls ${rvm_gems_path}/cache/${gem_file_name} 2> /dev/null | sort | head -n1)}"
    fi

    if [[ ! -s "$cache_file" ]] ; then
      if [[ -s "$gem_file_name" ]] ; then
        gem="$gem_file_name"
      elif [[ -z "${gem_version/ /}" ]] ; then
        gem="${gem_name/ /}"
      else
        gem="${gem_name/ /} -v $gem_version"
      fi
    else # cached
      gem_file_name="$(basename "$cache_file")"
      gem_string="$(echo "$gem_file_name" | sed 's#\.gem$##')"

      if [[ -z "$rvm_force_flag" ]] && [[ -s "${rvm_ruby_gem_home}/specifications/$(basename $gem_file_name)spec" ]] ; then
        unset gem # already installed, not forcing reinstall.
        $rvm_scripts_path/log "info" "$gem_name $gem_version exists, skipping (--force to re-install)"
      else
        if [[ -s "$rvm_gems_path/cache/$(basename $gem_file_name)" ]] ; then
          mkdir -p "$rvm_tmp_path/$$/"
          mv "$rvm_gems_path/cache/$gem_file_name" "$rvm_tmp_path/$$/$gem_file_name"
          gem="$rvm_tmp_path/$$/$gem_file_name -f -l"
        else
          gem="$cache_file"
        fi
      fi
    fi
  fi

  # If $gem is still set, go forward with the install.
  if [[ ! -z "$gem" ]] ; then
    # TODO: Set vars if fourth field is non-empty (means that there are conditional statements to execute in the gem install line.
    if [[ "rvm_make_flags_flag" -eq 1 ]] ; then __rvm_make_flags ; fi

    if [[ ! -z "$rvm_ruby_gem_home" ]] && [[ "$rvm_ruby_gem_home" != "$rvm_gems_path" ]] ; then
      #command="GEM_HOME='$rvm_ruby_gem_home' GEM_PATH='$rvm_ruby_gem_home/bin:$rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator}global/bin' BUNDLE_PATH='${rvm_ruby_gem_home}' ${gem_prefix} gem install --ignore-dependencies $gems_args $rvm_gem_options $gem_postfix $vars"
      command="GEM_HOME='$rvm_ruby_gem_home' GEM_PATH='$rvm_ruby_gem_home/bin:$rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator}global/bin' BUNDLE_PATH='${rvm_ruby_gem_home}' ${gem_prefix} gem install $gems_args $rvm_gem_options $gem_postfix $vars"
    else
      #--ignore-dependencies
      command="$gem_prefix gem install --ignore-dependencies $gems_args $rvm_gem_options -q $gem $gem_postfix $vars"
    fi
    __rvm_run "gem.install" "$command" "installing ${gem_name} ${gem_version}..."
    result=$?
    if [[ $result -eq 0 ]] ; then
      $rvm_scripts_path/log "info" "$gem_name $gem_version installed, output logged to:\n$rvm_path/log/$rvm_ruby_string/gem.install.log"
    else
      $rvm_scripts_path/log "error" "$gem_name $gem_version failed to install, output logged to:\n$rvm_path/log/$rvm_ruby_string/gem.install.error.log"
    fi
  fi ; unset gem gem_prefix gem_name gem_version gem_file_name gem_postfix cache_file gem_file_name gem_string gem_action

  return $result
}

# Output the user's current gem directory.
__rvm_gemset_gemdir() {
  if [[ "$rvm_user_flag" -eq 1 ]] ; then
    echo $(rvm system ; gem env | grep "\- $HOME" | awk '{print $NF}')
  elif [[ "$rvm_system_flag" -eq 1 ]] ; then
    echo $(rvm system ; gem env gemdir system)
  elif [[ ! -z "$rvm_ruby_string" ]] ; then
    echo $(rvm "$rvm_ruby_string" ; gem env gemdir)
  elif [[ ! -z "$GEM_HOME" ]] ; then
    echo "$GEM_HOME"
  else
    gem env gemdir
  fi
}

__rvm_gem_pristine() {
  gem pristine --all
}

unset GEM_PATH

if ! command -v gem > /dev/null ; then
  $rvm_scripts_path/log "error" "'gem' was not found, cannot perform gem actions (Do you have an RVM ruby selected?)"
  exit 1
fi

action="$(echo $* | awk '{print $1}')"
gems_args=$(echo "$*" | awk '{$1="" ; print}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
export rvm_gemset_name

if [[ "import" = "$action" ]] || [[ "load" = "$action" ]] ; then
  __rvm_gemset_import
elif [[ "export" = "$action" ]] || [[ "dump" = "$action" ]] ; then
  __rvm_gemset_export
elif [[ "create" = "$action" ]] ; then
  __rvm_gemset_create
elif [[ "copy" = "$action" ]] ; then
  __rvm_gemset_copy
elif [[ "empty" = "$action" ]] ; then
  __rvm_gemset_empty
elif [[ "delete" = "$action" ]] ; then
  __rvm_gemset_delete
elif [[ "name" = "$action" ]] || [[ "string" = "$action" ]]; then
  __rvm_gemset_name
elif [[ "dir" = "$action" ]] ; then
  __rvm_gemset_dir
elif [[ "list" = "$action" ]] ; then
  __rvm_gemset_list
elif [[ "gemdir" = "$action" ]] ; then
  __rvm_gemset_gemdir
elif [[ "install" = "$action" ]] ; then
  __rvm_gem_install $*
elif [[ "pristine" = "$action" ]] ; then
  __rvm_gem_pristine $*
elif [[ "clear" = "$action" ]] ; then
  $rvm_scripts_path/log "info" "gemset cleared."
  exit 0
else
  $rvm_scripts_path/log "error" "Unrecognized gemset action '$action'.\n\nValid gems actions are: {create,use,import,export,copy,delete,empty,name,list,gemdir,install}"
fi

exit $?
