#!/usr/bin/env bash

source "$rvm_scripts_path/base"

get_usage()
{
  cat -v "$rvm_help_path/get"
}

get_via_installer()
{
  bash -s -- $@ < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer) || return $?

  rvm_log "\nInstalled RVM version:"
  ( source $rvm_scripts_path/rvm ; rvm --version )

  typeset -x rvm_hook
  rvm_hook="after_update"
  source "$rvm_scripts_path/hook"

  return 0
}

export args
args=($*)
action="${args[$__array_start]}"
args[$__array_start]=""
args=(${args[@]})

# handle rvm get --auto head, --auto goes to the end
if [[ "$action" == "--auto" ]]
then
  action="${args[$__array_start]}"
  args[$__array_start]=""
  args=(${args[@]} --auto)
fi

case "$action" in
  (latest|latest-*|[0-9]*.[0-9]*.[0-9]*)
    get_via_installer --version $action ${args[@]}
    ;;

  (version)
    get_via_installer --version ${args[@]}
    ;;

  (stable|master)
    get_via_installer --branch $action ${args[@]}
    ;;

  (head)
    get_via_installer --branch master ${args[@]}
    ;;

  (branch)
    get_via_installer --branch ${args[@]}
    ;;

  (help)
    get_usage
    true
    ;;

  (*)
    get_usage
    false
    ;;
esac

exit $?
