#!/usr/bin/env bash

source $rvm_scripts_path/initialize

if [[ ! -z "$rvm_trace_flag" ]] ; then set -x ; export rvm_trace_flag ; fi

trap "if [[ -d $rvm_tmp_path/ ]] && [[ -s $rvm_tmp_path/$$ ]] ; then rm -f $rvm_tmp_path/$$ > /dev/null 2>&1 ; fi ; exit" 0 1 2 3 15

rvm_help_path="${rvm_help_path:-"$rvm_path/help"}"

command="$(echo $* | awk '{print $1}')"
action="$(echo $* | awk '{print $2}')"
# Reserved for future use:
args=$(echo "$*" | awk '{$1=""; $2="" ; print}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

if [[ ! -z "$command" ]] && [[ -s "${rvm_help_path}/${command}" ]] ; then
  if [[ ! -z "$action" ]] && [[ -s "${rvm_help_path}/${command}/${action}" ]] ; then
    cat "${rvm_help_path}/${command}/${action}" | ${PAGER:-less}
  else
    cat "${rvm_help_path}/${command}" | ${PAGER:-less}
  fi
else
  cat "${rvm_path:-$HOME/.rvm}/README" | ${PAGER:-less}
  $rvm_scripts_path/log "info" "\nFor help with a specific command:\n $(builtin cd "${rvm_help_path}" ; \ls)"
fi

$rvm_scripts_path/log "info" "\nFor additional information please visit RVM's documentation website:\n    http://rvm.beginrescueend.com/\n"

exit $?
