#!/usr/bin/env bash

if [[ ! -z "$rvm_hook" ]] ; then
  if [[ -s "$rvm_hooks_path/$rvm_hook" ]] ; then
    if [[ "$rvm_verbose_flag" -eq 1 ]] || [[ "$rvm_debug_flag" -eq 1 ]] ; then $rvm_scripts_path/log "info" "running hook $rvm_hook" ; fi
    source "$rvm_hooks_path/$rvm_hook"
  fi
fi ; unset rvm_hook
