#!/usr/bin/env bash

if [[ "root" = "$(whoami)" ]] ; then
  rvm_rc_files="/etc/profile /etc/zshenv"
else
  rvm_rc_files="$HOME/.bash_profile $HOME/.bashrc $HOME/.zshenv"
fi

if [[ ! -z "$rvm_archflags" ]] ; then rvm_make_flags_flag=1 ; fi

rvm_project_rvmrc="${rvm_project_rvmrc:-1}"
rvm_project_rvmrc_default="${rvm_project_rvmrc_default:-0}"
if [[ -z "$rvm_scripts_path" ]] ; then
  if [[ -d "$HOME/scripts" ]] && [[ -f "/usr/local/rvm/scripts/rvm" ]]; then
    rvm_scripts_path="$HOME/scripts"
  elif [[ -d "/usr/local/rvm/scripts" ]] && [[ -f "/usr/local/rvm/scripts/rvm" ]] ; then
    rvm_scripts_path="/usr/local/rvm/scripts"
  else
    rvm_scripts_path="$rvm_path/scripts"
  fi
fi
rvm_archives_path="${rvm_archives_path:-"$rvm_path/archives"}"
rvm_src_path="${rvm_src_path:-"$rvm_path/src"}"
rvm_log_path="${rvm_log_path:-"$rvm_path/log"}"
rvm_bin_path="${rvm_bin_path:-"$rvm_path/bin"}"
rvm_gem_path="${rvm_gem_path:-"$rvm_path/gems"}"
rvm_config_path="${rvm_config_path:-"$rvm_path/config"}"
rvm_hooks_path="${rvm_hooks_path:-"$rvm_path/hooks"}"
rvm_tmp_path="${rvm_tmp_path:-"$rvm_path/tmp"}"
rvm_symlink_path="${rvm_symlink_path:-/usr/local/bin}"

export rvm_path rvm_scripts_path rvm_archives_path rvm_src_path rvm_log_path rvm_bin_path rvm_gem_path rvm_config_path rvm_tmp_path

__rvm_initialize
