#!/usr/bin/env bash

# Ensure that the extended globs feature is turned on.
if [[ -n "${ZSH_VERSION:-""}" ]] ; then
  setopt extendedglob
else
  if [[ -n "${BASH_VERSION:-""}" ]] ; then
    shopt -s extglob # Extended globs
  else
    printf "%s\n" "What the heck kind of shell are you running here???"
  fi
fi

if [[ ${rvm_selfcontained:-1} -eq 0 ]] ; then
  rvm_bin_path="${rvm_bin_path:-"${rvm_prefix}bin"}"
  rvm_man_path="${rvm_man_path:-"${rvm_prefix}share/man"}"
  rvm_rc_files="${rvm_rc_files:-"/etc/profile /etc/zshenv"}"
else
  rvm_man_path="${rvm_man_path:-"$rvm_path/man"}"
  rvm_bin_path="${rvm_bin_path:-"$rvm_path/bin"}"
  rvm_rc_files="${rvm_rc_files:-"$HOME/.bash_profile $HOME/.bashrc $HOME/.zshenv"}"
fi

[[ -n "${rvm_archflags:-""}" ]] && rvm_make_flags_flag=1

rvm_docs_path="${rvm_docs_path:-"$rvm_path/docs"}"

rvm_gems_path="${rvm_gems_path:-"$rvm_path/gems"}" # Leave this one in global, need to override for system installs (for now).
rvm_gems_cache_path="${rvm_gems_cache_path:-"$rvm_gems_path/cache"}"

rvm_tmp_path="${rvm_tmp_path:-"$rvm_path/tmp"}"

export rvm_path rvm_bin_path rvm_gems_path rvm_tmp_path rvm_gems_cache_path rvm_gemset_separator rvm_selfcontained

