#!/usr/bin/env bash

if [[ "root" = "$(whoami)" ]] ; then
  rvm_rc_files="${rvm_rc_files:-"/etc/profile /etc/zshenv"}"
else
  rvm_rc_files="${rvm_rc_files:-"$HOME/.bash_profile $HOME/.bashrc $HOME/.zshenv"}"
fi

if [[ ! -z "$rvm_archflags" ]] ; then rvm_make_flags_flag=1 ; fi

rvm_project_rvmrc="${rvm_project_rvmrc:-1}"
rvm_project_rvmrc_default="${rvm_project_rvmrc_default:-0}"

rvm_archives_path="${rvm_archives_path:-"$rvm_path/archives"}"
rvm_src_path="${rvm_src_path:-"$rvm_path/src"}"
rvm_log_path="${rvm_log_path:-"$rvm_path/log"}"
rvm_bin_path="${rvm_bin_path:-"$rvm_path/bin"}"

if [[ "root" = "$(whoami)" ]] ; then
  rvm_gems_path="${rvm_gems_path:-"$rvm_path/gems"}"
  rvm_gems_cache_path="${rvm_gems_cache_path:-"$rvm_gems_path/cache"}"
else
  rvm_gems_path="${rvm_gems_path:-"$HOME/.rvm/gems"}"
  rvm_gems_cache_path="${rvm_gems_cache_path:-"$HOME/.gem/cache"}"
fi

rvm_rubies_path="${rvm_rubies_path:-"$rvm_path/rubies"}"
rvm_config_path="${rvm_config_path:-"$rvm_path/config"}"
rvm_hooks_path="${rvm_hooks_path:-"$rvm_path/hooks"}"
rvm_tmp_path="${rvm_tmp_path:-"$rvm_path/tmp"}"
rvm_usr_path="${rvm_usr_path:-"$rvm_path/usr"}"
rvm_symlink_path="${rvm_symlink_path:-$rvm_prefix/bin}"

export rvm_path rvm_rubies_path rvm_scripts_path rvm_archives_path rvm_src_path rvm_log_path rvm_bin_path rvm_gems_path rvm_config_path rvm_tmp_path rvm_hooks_path rvm_gems_cache_path

