#!/usr/bin/env bash

# When rvm_silence_logging is set, don't show anything.
[[ -n "$rvm_silence_logging" ]] && exit 0

if [[ "$rvm_trace_flag" -eq 2 ]] ; then set -x ; export rvm_trace_flag ; fi

if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi

message="${1//\%/%%}"

if [[ ${rvm_pretty_print_flag:-0} -eq 0 ]] ; then

  if [[ ${rvm_verbose_flag:-0} -gt 0 && -n "$level" ]] ; then
    message="$level: $message"
  fi

  case "$level" in
    info)       printf "%s\n" "${message#*: }" ;;
    debug|warn) printf "%s\n" "$message" ;;
    error|fail) printf "%s\n" "$message" >&2  ;;
    *) printf "$message"
  esac

else

  case "$level" in
    debug) printf "%s\n" "$(tput setaf 5)$level$(tput sgr0): $message"     ;;
    info)  printf "%s\n" "$(tput setaf 2)$level$(tput sgr0): $message"     ;;
    warn)  printf "%s\n" "$(tput setaf 3)$level$(tput sgr0): $message"     ;;
    error) printf "%s\n" "$(tput setaf 1)$level$(tput sgr0): $message" >&2 ;;
    fail)  printf "%s\n" "$(tput setaf 1)$level$(tput sgr0): $message" >&2 ;;
    *)     printf "%s\n" "$message"
  esac

fi

exit 0
