#!/usr/bin/env bash

# When rvm_silence_logging is set, don't show anything.
[[ -n "$rvm_silence_logging" ]] && exit 0

if [[ "$rvm_trace_flag" -eq 2 ]] ; then set -x ; export rvm_trace_flag ; fi

if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi

message="${1//%/%%}"

rvm_pretty_print=${rvm_pretty_print:-0}
if [[ $rvm_pretty_print -eq 0 ]] ; then
  if [[ $rvm_verbose_flag -eq 1 ]] && [[ -n "$level" ]] ; then
    message="$level: $message"
  fi

  case "$level" in
    debug|info|warn) printf "\n$message\n"     ;;
    error|fail) printf "\n$message\n" >&2 ;;
    *) printf "$message"
  esac
else
  case "$level" in
    debug) printf "\n$(tput setaf 5)$level$(tput sgr0): $message\n"     ;;
    info)  printf "\n$(tput setaf 2)$level$(tput sgr0): $message\n"     ;;
    warn)  printf "\n$(tput setaf 3)$level$(tput sgr0): $message\n"     ;;
    error) printf "\n$(tput setaf 1)$level$(tput sgr0): $message\n" >&2 ;;
    fail)  printf "\n$(tput setaf 1)$level$(tput sgr0): $message\n" >&2 ;;
    *) printf "$message"
  esac
fi

exit 0
