#!/usr/bin/env bash

source "$rvm_scripts_path/initialize"

# Take if a semicolon is encountered at the end of the
# manpath env variable, man also processes the usual,
# generated manpaths as well as the variable contents.
export MANPATH="${rvm_man_path}:${MANPATH}"
