#!/usr/bin/env bash

if [[ -z "$1" ]] || [[ -z "$2" ]] ; then
  exit 1
fi

if [[ ! -z "$BASH_VERSION" ]] && [[ ${BASH_VERSION:0:1} -gt 2 ]] ; then
  [[ "$1" =~ $2 ]]
  exit $?
else
  if [ ! -z "$(echo "$1" | awk "/${2}/")" ] ; then
    exit 0
  else
    exit 1
  fi
fi
