#!/usr/bin/env bash

 printf "\n\033[32mNOTE:\033[0m
As of 1.8.0 RVM once again loads .rvmrc files, by default, after asking your
permission to trust it of course.  If you do not wish to be enabled, simply set:
    export rvm_project_rvmrc=0
Within either your /etc/rvmrc or \$HOME/.rvmrc file. This will turn off the
cd/pushd hooks when sourcing the rvm() function into your shell.
\n"

 printf "\n\r \033[32mExample: echo 'export rvm_project_rvmrc=0' >> \$HOME/.rvmrc;
 (Then close the current shell and open a new one.)\n
 If you wish to add this for all users, exchange \$HOME/.rvmrc with /etc/rvmrc\033[0m\n"
 
 printf "\n\r All individual additional OS requirements/dependencies are now contained in 'rvm requirements'\n"

 printf "\n\r \033[32mRVM Group Membership Management\033[0m - With Multi-User installations, the RVM installer automatically
 creates an 'rvm' group which, as the RVM documentation explains, administrators must add the users they wish
 to let use the RVM installation to. The call is made in the installer as:\n
     \033[32msudo dscl . -create /Groups/\$rvm_group_name gid \$gid\033[0m\n
 wherein RVM creates the gid by checking for the last assigned gid and adding 1. To physicially add a user to
 the group, administrators must use:\n
     \033[32msudo dscl localhost -append /Local/Default/Groups/rvm GroupMembership \$user_name\033[0m\n
 Afterwards, should administrators wish to remove users from the group, they would execute:\n
     \033[32msudo dscl localhost -delete /Local/Default/Groups/rvm GroupMembership \$user_name\033[0m
     \033[32msudo dsmemberutil flushcache\033[0m\n
 This will keep the 'rvm' group, but remove the listed user from it. They can directly delete the rvm group with:\n
     \033[32msudo dscl . -delete /Groups/rvm && sudo dsmemberutil flushcache\033[0m\n
 without previously deleting users from the group, as well. This will completely remove the 'rvm' group from the system.
 Please note, the call to 'dsmemberutil flushcache' is required on both removal of the user from the group, and/or 
 removal of the group directly because that membership is still cached locally until either reboot or sync with 
 Directory Services. Allowing the group membership to stay in the user's 'groups' output does not mean the user is 
 automatically re-added to the 'rvm' group should the group be subsequently be re-added. This means the user(s) end up 
 erroneously showing they are part of the 'rvm' group even though they actually are not, if the call to 'dsmemberutil' 
 is not made. By this we mean the 'groups' command will still show them a part of the 'rvm' group, even if the user 
 logs out and then back in, due to caching. This applies to Tiger, Leopard, Snow Leopard, and Lion. Previous versions of 
 the OS such as Cheetah/Puma, and Jaguar used 'nicl', a.k.a NetInfo, and not 'dscl'.\n"

echo

