#!/usr/bin/env bash

source "$rvm_scripts_path/functions/osx-ssl-certs"

__rvm_osx_ssl_certs_status()
{
}

__rvm_osx_ssl_certs_update()
{
}

__rvm_osx_ssl_certs_cron_status()
{
}

__rvm_osx_ssl_certs_cron_install()
{
}

__rvm_osx_ssl_certs_cron_uninstall()
{
}

__rvm_osx_ssl_certs_cron()
{
  typeset cron_action="${1:-status}"
  shift 1
  case "${cron_action}" in
    (status|install|uninstall)
      __rvm_osx_ssl_certs_cron_${cron_action}
      ;;
    (help)
      rvm_help osx-ssl-certs cron "$@"
      ;;
    (*)
      rvm_error_help "Unknown subcommand '$*' for osx-ssl-certs cron" osx-ssl-certs cron "$@"
      return 1
      ;;
  esac
}

__rvm_osx_ssl_certs()
{
  typeset action="${1:-status}"
  shift 1
  case "${action}" in
    (status|update|cron)
      __rvm_osx_ssl_certs_${action} "$@"
      ;;
    (help)
      rvm_help osx-ssl-certs "$@"
      ;;
    (*)
      rvm_error_help "Unknown subcommand '$*' for osx-ssl-certs" osx-ssl-certs "$@"
      return 1
      ;;
  esac
}

__rvm_osx_ssl_certs "${args[@]}"
