#!/usr/bin/env bash

if [[ ${rvm_leave_gem_alone:-0} -eq 0 ]]; then
  function gem
  {
    (
    typeset result rvmrc
    for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
    do [[ -s "$rvmrc" ]] && source "$rvmrc" || true
    done
    command gem "$@" || result=$?
    hash -r
    return ${result:-0}
    )
  }
fi
