#!/usr/bin/env bash

# General tools for manipulating patches
# and dealing with patches.

# Returns the path used to look for a patch given a specific name.
__rvm_patch_lookup_path() {
  echo "" 
  [[ -n "$rvm_patch_original_pwd" ]] && echo "$rvm_patch_original_pwd/"
  echo "$PWD/"
  __rvm_ruby_string_paths_under "$rvm_patches_path" | sed 's/$/\//'
}

# Return the full patch for a given patch.
__rvm_lookup_full_patch_path() {
  # Absolute path, pwd and then finally the rvm patches path.
  for directory in $(__rvm_patch_lookup_path) ; do
    for extension in {"",.patch,.diff}; do
      patch_path="${directory}${1}${extension}"
      if [[ -s "$patch_path" ]]; then
        echo "$patch_path"
        return
      fi
    done; unset extension patch_path
  done; unset directory
  return 1
}
