#!/usr/bin/env bash

rvm_base_except="selector"
source "$rvm_scripts_path/base"
source "$rvm_scripts_path/patches"

lookup_patchset() {
  if [[ -z "$1" ]]; then
    echo "Usage: rvm patchset show name"
    return 1
  fi
  for lookup_path in $(__rvm_ruby_string_paths_under "$rvm_patchsets_path") ; do
    if [[ -s "$lookup_path/$1" ]]; then
      cat "$lookup_path/$1"
      return
    fi
  done; unset lookup_path
  return 1
}

# Return the full patch for a given patch.
__rvm_lookup_full_patch_path() {
  # Absolute path, pwd and then finally the rvm patches path.
  for directory in $(__rvm_patch_lookup_path) ; do
    for extension in {"",.patch,.diff}; do
      patch_path="${directory}${1}${extension}"
      if [[ -s "$patch_path" ]]; then
        echo "$patch_path"
        return
      fi
    done; unset extension patch_path
  done; unset directory
  return 1
}

usage() {
  echo "Usage: 'rvm patchset {show,lookup}'"
  echo "        Tools for manipulating patchsets."
  return 1
}

case "$1" in
  show|lookup) lookup_patchset "$2" ;;
  *) usage ;;
esac

exit $?
