#!/usr/bin/env bash

rvm_url="http://rvm.beginrescueend.com/"

if command -v open >/dev/null ; then

  open "$rvm_url"

elif command -v xdg-open >/dev/null ; then

  xdg-open "$rvm_url"

else

  "$rvm_path/scripts"/log "info" \
    "Please RTFM at the URL $rvm_url"

fi

exit $?
