#!/usr/bin/env bash

# rvm : Ruby Version Manager
# http://rvm.beginrescueend.com
# http://gitub.com/wayneeseguin/rvm

if [[ "$rvm_loaded_flag" != "1" ]] || [[ "$rvm_reload_flag" = "1" ]] ; then
  unset rvm_reload_flag

  if [[ -f /etc/rvmrc ]] ; then source /etc/rvmrc ; fi
  if [[ -f "$HOME/.rvmrc" ]] ; then source "$HOME/.rvmrc" ; fi

  if [[ -z "$rvm_path" ]] ; then
    unset rvm_path
    if [[ "root" = "$(whoami)" ]] ; then
      rvm_path="/usr/local/rvm"
    else
      if [[ -d "$HOME/.rvm" ]] && [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
        rvm_path="$HOME/.rvm"
      elif [[ -d "/usr/local/rvm" ]] && [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
        rvm_path="${rvm_path:-"/usr/local/rvm"}"
      fi
    fi
  fi
  if [[ -d "$rvm_path" ]] ; then
    rvm_scripts_path="${rvm_scripts_path:-"$rvm_path/scripts"}"
    source $rvm_scripts_path/array
    source $rvm_scripts_path/utility
    source $rvm_scripts_path/initialize
    source $rvm_scripts_path/version
    source $rvm_scripts_path/selector
    source $rvm_scripts_path/cli
    #source $rvm_scripts_path/gems
    source $rvm_scripts_path/libraries
    source $rvm_scripts_path/cd

    rvm_loaded_flag=1

    rvm_version="$(cat "${rvm_path}/lib/VERSION.yml" | tail -n 3 | sed 's/^.*: //g' | tr "\n" '.' | sed 's/\.$//')" ; export rvm_version

    alias rvm-restart="source '${rvm_path}/scripts/rvm'"

    if [[ -s "$HOME/.rvm/default" ]] ; then
      source "$HOME/.rvm/default"
    elif [[ -s "$rvm_config_path/default" ]] ; then
      source "$rvm_config_path/default"
    elif [[ -s "/usr/local/rvm/config/default" ]] ; then
      source "/usr/local/rvm/config/default"
    fi
  else
    echo -e "\$rvm_path is not set. rvm cannot load."
  fi
fi

