#!/bin/bash

#
# rvm : Ruby Version Manager
# http://rvm.beginrescueend.com
# http://gitub.com/wayneeseguin/rvm
#

if [ -s ~/.rvmrc ] ; then source ~/.rvmrc ; fi
eval rvm_path="${rvm_path:-~/.rvm}"

source $rvm_path/scripts/utility
source $rvm_path/scripts/selector
source $rvm_path/scripts/ruby-installer # TODO: Script not function.
source $rvm_path/scripts/cli

if [ -f $rvm_path/default ] ; then source $rvm_path/default ; fi

