#!/bin/bash

user=`whoami`
if [ "$user" = "root" ] ; then
  echo -e "\033[0;31m <e> \033[0mroot user support is not implemented yet.\033[0m"
  exit 1
fi

info="\n\033[0;32m<i>\033[0m"

echo -e "$info Updating rvm source ~/.rvm/scripts/rvm ..."
mkdir -p ~/.rvm/src ~/.rvm/scripts
for script in rvm ; do # Prepairing for refactoring.
  cp "`dirname "${0}"`/$script" ~/.rvm/scripts/
done
cp "`dirname "${0}"`/../examples/rvmrc" ~/.rvm/examples/

echo -e "$info There have been a great many updates since previous releases, please:"
echo -e "$info   * remove sourcing of ~/.rvm/current from your shell profiles."
echo -e "$info   * note that gems are now all pulled into ~/.rvm/gems/"

echo -e "\n    Thank you, come again! \n"
echo -e "        ~ Wayne"

source ~/.rvm/scripts/rvm
rvm symlinks

