#!/bin/bash
if [[ ! -z "$(which ruby | awk '/\.rvm/{print}')" ]] ; then
  command=$(which ruby)
  if [[ ! -z "$command" ]] ; then
    echo "[$(echo $command | xargs dirname | xargs dirname | xargs basename | tr '-' ':')]"
  fi ; unset command
fi

