#!/usr/bin/env bash

__rvm_meta()
{
  rvm_meta_authors=(
    "Michal Papis"
    "Piotr Kuczynski"
    "Wayne E. Seguin"
  )
  rvm_meta_website="https://rvm.io/"
  rvm_meta_version="${rvm_version}"
}

__rvm_version()
{
  __rvm_meta

  \typeset IFS release
  IFS=':'
  rvm_meta_authors="${rvm_meta_authors[*]}"
  rvm_meta_authors="${rvm_meta_authors//:/, }"

  echo "rvm ${rvm_meta_version} by ${rvm_meta_authors} [${rvm_meta_website}]"
}
