#!/bin/bash

user=`whoami`
if [ "$user" = "root" ] ; then 
  echo -e "\e[0;31m <e> \e[0mroot user support is not yet implemented.\e[0m"
  exit 1
fi

info="\n\e[0;32m<i>\e[0m"

echo -e "$info Updating rvm source ~/.rvm/bin/rvm ..."
mkdir -p ~/.rvm/src ~/.rvm/bin
cp $(pwd)/bash/rvm ~/.rvm/bin/

echo -e "     Thank you, come again! \n"
echo -e "       ~ Wayne"

source ~/.rvm/bin/rvm

