#!/bin/bash

mkdir -p ~/.bin/

cwd=`pwd`
if [ ! -d ~/.bin -o ! -f ~/.bin/rvm -o ! -e ~/.bin/rvm ] ; then
  rm -f ~/.bin/rvm
  echo "Installing ~/.bin/rvm"
  ln -fs $cwd/bash/rvm ~/.bin/rvm
  chmod +x ~/.bin/rvm
fi

touch ~/.bash_profile

if [ -z "`grep '\.bin' ~/.bash_profile`" ] ; then
  echo "Adding '~/.bin' to your path."
  echo "PATH=~/.bin:\$PATH ; export PATH" >> ~/.bash_profile
fi

if [ -z "`grep '\.rvmrc' ~/.bash_profile`" ] ; then
  echo "Adding 'source ~/.rvmrc' ~/.bash_profile."
  echo "if [ -f ~/.rvmrc ] ; then source ~/.rvmrc ; fi" >> ~/.bash_profile
fi

source ~/.bash_profile

