#!/bin/bash

user=`whoami`
if [ "$user" = "root" ] ; then
  echo -e "\033[0;31m <e> \033[0mroot user support is not yet implemented.\033[0m"
  exit 1
fi

info="\n\033[0;32m<i>\033[0m"
question="\n\033[0;32m<?>\033[0m"

echo -e "Installing rvm source to ~/.rvm/bin/rvm..."
mkdir -p ~/.rvm/src ~/.rvm/bin
for script in rvm ; do # Preparing for refactoring.
  cp bash/$script ~/.rvm/bin/
done


# State what is required to use rvm
echo -e "\n\033[0;32mrvm\033[0m is a shell script that allows a user to manage multiple ruby versions in their own account."
echo -e "$info In order to use rvm the following line must occur in your shell's loading files:"
echo -e "\n\033[0;32m    (a)\033[0m if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi"

while : ; do
  echo -n -e "$question Do you want this (s)cript to set this up for you, or do it (m)anually yourself ('s' or 'm')? "
  read response
  if [ "${response:0:1}" = "s" ] ; then
    echo 'w00t!'
    break
  elif [ "${response:0:1}" = "m" ] ; then
    echo -e "$info Please make sure that both lines (a) and (b) are in place, with (a) sourced *first*."
    break
  fi
done

if [ "${response:0:1}" = "s" ] ; then

  while : ; do
    echo -n -e "$question Do you use b(a)sh or (z)sh or b(o)th for your shell (the default on most *nix systems is bash, press control + C to cancel the installation)\n(a/z/o)? "
    read response
    if [ "${response:0:1}" = "a" ] ; then
      user_shell="bash"
      break
    elif [ "${response:0:1}" = "z" ] ; then
      user_shell="zsh"
      break
    elif [ "${response:0:1}" = "o" ] ; then
      user_shell="both"
      break
    fi
  done

  if [ "$user_shell" = "bash" -o "$user_shell" = "both" ] ; then

    touch ~/.bash_profile
    if [ -z "`grep '\.rvm/bin/rvm' ~/.bash_profile`" ] ; then
      echo "Adding 'if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi' to your ~/.bash_profile."
      echo "if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi" >> ~/.bash_profile
    fi
    touch ~/.bashrc
    if [ -z "`grep '\.rvm/bin/rvm' ~/.bashrc`" ] ; then
      echo "Adding 'if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi' to your ~/.bashrc."
      echo "if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi" >> ~/.bashrc
    fi

  fi

  if [ "$user_shell" = "zsh" -o "$user_shell" = "both" ] ; then

    touch ~/.zshrc
    if [ -z "`grep '\.rvm/bin/rvm' ~/.zshrc`" ] ; then
      echo "Adding 'if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi' to your ~/.zshrc."
      echo "if [ -f ~/.rvm/bin/rvm ] ; then source ~/.rvm/bin/rvm ; fi" >> ~/.zshrc
    fi
  fi

fi

system=`uname`
if [ "$system" = "Linux" ] ; then
  rvm_apt_get_binary=`which apt-get`
  rvm_emerge_binary=`which emerge`
  rvm_pacman_binary=`which pacman`
  rvm_yum_binary=`which yum`

  echo -e "\033[0;33m <w> \033[0mFor jRuby (if you wish to use it) you will need:"
  if [ ! -z "$rvm_apt_get_binary" ] ; then
    echo -e "\033[0;32m <i> \033[0msudo apt-get install sun-java6-bin sun-java6-jre sun-java6-jdk  "
  elif [ ! -z "$rvm_emerge_binary" ] ; then
    echo -e "\033[0;32m <i> \033[0msudo emerge dev-java/sun-jdk dev-java/sun-jre-bin"
  elif [ ! -z "$rvm_pacman_binary" ] ; then
    echo -e "\033[0;32m <i> \033[0msudo pacman -Sy jdk jre"
  elif [ ! -z "$rvm_yum_binary" ] ; then
    echo -e "\033[0;32m <i> \033[0myum install -y rpm-build gcc gcc-c++ redhat-rpm-config ; then download and rpmbuild and install the sdk, Have fun..."
  else
    echo -e "\033[0;32m <i> \033[0mThe SUN java runtime environment and development kit."
  fi
#elif [ "$sytem" = "Darwin" ] ; then
#else
fi

source ~/.rvm/bin/rvm
rvm symlinks

echo -e "\n$info If you add ~/.rvm/bin/ to your path you will be able to refer to installed ruby binaries using: <implementation>-<version><patchlevel>"
echo -e "     For example: ruby-1.9.1-p243 -e 'puts \"hello world\"' #=> hello world"
echo -e "$info Contact wayneeseguin on irc.freenod.net in #rvm for any questions / feedback."
echo -e "     I truly hope that you find rvm helpful! Thank you very much for using rvm. \n"
echo -e "       ~ Wayne"

echo -e "$info To start using rvm see: \033[0;32m rvm usage\033[0m, Now close this login shell and open a new one."

