#!/bin/bash

mkdir -p ~/.rvm/src ~/.rvm/bin

cp $(pwd)/bash/rvm ~/.rvm/bin/

touch ~/.profile
if [ -z "`grep '\.rvm/bin/rvm' ~/.profile`" ] ; then
  echo "Adding 'source ~/.rvm/bin/rvm' to your ~/.profile."
  echo "source ~/.rvm/bin/rvm" >> ~/.profile
fi

if [ -z "`grep '\.rvm/current' ~/.profile`" ] ; then
  echo "Adding 'source ~/.rvm/current' ~/.profile."
  echo "if [ -f ~/.rvm/current ] ; then source ~/.rvm/current ; fi" >> ~/.profile
fi

touch ~/.bash_profile
if [ -z "`grep '\.profile' ~/.bash_profile`" ] ; then
  echo "Adding 'source ~/.profile' to the end of ~/.bash_profile."
  echo "if [ -f ~/.profile ] ; then source ~/.profile ; fi" >> ~/.bash_profile
fi

touch ~/.zprofile
if [ -z "`grep '\.profile' ~/.zprofile`" ] ; then
  echo "Adding 'source ~/.profile' to the end of ~/.zprofile."
  echo "if [ -f ~/.profile ] ; then source ~/.profile ; fi" >> ~/.zprofile
fi

echo -e "\n\e[0;32mOpen a new shell and enjoy rvm: rvm usage\e[0m\n"

