#!/bin/bash

mkdir -p ~/.bin/

if  [ ! -s ~/.bin/rvm ] ; then
  ln -fs `pwd`/bash/rvm ~/.bin/rvm
fi

grep "~/.bin" ~/.bash_profile
if [ $? != 0 ] ; then
  echo "PATH=~/.bin:\$PATH" >> ~/.bash_profile
fi

source ~/.bash_profile

