#!/bin/bash

user=`whoami`
if [ "$user" = "root" ] ; then 
  echo -e "\033[0;31m <e> \033[0mroot user support is not yet implemented.\033[0m"
  exit 1
fi

info="\n\033[0;32m<i>\033[0m"

echo -e "$info Updating rvm source ~/.rvm/bin/rvm ..."
mkdir -p ~/.rvm/src ~/.rvm/bin
cp $(pwd)/bash/rvm ~/.rvm/bin/

echo -e "\n    Thank you, come again! \n"
echo -e "        ~ Wayne"

source ~/.rvm/bin/rvm

rvm-symlinks

